src/app/body/board/sprint-details/sprint-details.component.html
Signed-off-by: AvinashMahanthi <avinashfab5678@gmail.com>
Remove sprint 'Details' row from the dashboard
Removed the div related to the sprint-Details
- ng serve
- firebase emulators:start
- Go to the Board
Screenshot:
=> feat(sprint-details): Deleted Sprint Details

src/app/body/board/board.component.html, src/app/body/board/board.component.ts, src/app/body/board/focus-nav/focus-nav.component.ts, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/board/sprint-details/sprint-details.component.ts, src/app/body/create-new-sprint/create-new-sprint.component.ts, src/app/services/backend.service.ts
Whenever we filter and change the sprint number and view the task details page and return to the board page, the sprint number will remain unchanged.
Made the backend Service hold the value of Sprint Number and used it in the board component.
1. firebase emulators:start.
2. ng serve.
3. Create 2 new sprints and filter to the non-current Sprint.
4. Go to any of the tabs (say Development).
5. Go back to Board and see the sprint Number unchanged.
=> Made the backend Service to handle the change in sprint number.

src/app/header/header.component.html, src/app/services/backend.service.ts
Shows the collapse button in mobile view for navbar and also does not flood console during sprint change
Added the collapse button in navbar.
Removed the console.log lines in backendService.ts file that were flooding console when a sprint was changed.
2. ng serve
3. Change a sprint name and view console.
4. Use mobile view and button will be seen on navbar
=> UI Bug fixes

src/app/body/task-details/edit-page/edit-page.component.html
Solves the error where the assignee name wouldn't get edited in the edit page.
Corrected the error in the assignee variable name.
1. firebase emulators:start 
2. ng serve
3. Try to edit a task after creating the task and sprint.
=> Solved bug in edit page where assignee would not get changed

src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts
Allows us to reopen and edit and log work to a task that was previously marked as "Completed".
Made a function that uses log work API and made changes in the values to mark it as "Ready to start" from "Completed".
2. ng serve
3. Try to log work to a task after creating the task and sprint and mark it as Completed.
4. Go to the task details page for that task and click on the restore button to reopen the task.
=> Made a repoen task button to reopen a task that is marked as Completed.

functions/createNewTaskAPI.js, functions/editPageTaskAPI.js
Earlier when we were migrating a task to a non-existing sprint, new sprint was not getting created.
Made changes to editTaskAPI ,fetched details like teamID, orgID which are needed while creating a new sprint
ng serve
Edit a task and give a non-existing sprint number.
=> feat(editTaskFixes): Fixed EditTaskAPI

src/app/body/body.component.ts, src/app/body/home/home.component.html, src/app/body/home/home.component.ts
Signed-off-by: Akshay-Jak <akshayjani2147@gmail.com>
If a user has anAppKey on opening worktrolly, he is directly led to the My Dashboard page instead of home page
Made changes in home.component.html, home.component.ts and body.component.ts
ng serve
=> Directing the logged in user to MyDashboard Page

functions/model/patch/patch1.js
There was a typing error in patch1 file. The variable 'fullSprintId' was not typed correctly which was causing errors while running patch1.
Corrected it.
ng serve
Try running Patch1.
=> Feat(dev/bugFix): Fixed the bug in Patch1

src/app/body/create-new-task/create-new-task.component.ts, src/app/body/quick-notes/addnew-note/addnew-note.component.css, src/app/body/quick-notes/addnew-note/addnew-note.component.html, src/app/body/quick-notes/addnew-note/addnew-note.component.ts, src/app/body/quick-notes/edit-note/edit-note.component.css, src/app/body/quick-notes/edit-note/edit-note.component.html, src/app/body/quick-notes/edit-note/edit-note.component.ts, src/app/body/quick-notes/quick-notes.component.css, src/app/body/quick-notes/quick-notes.component.html, src/app/body/quick-notes/quick-notes.component.ts, src/app/services/popup-handler/popup-handler.service.ts
- Added Create A Task from Quick Notes
- Changed the colour of the quick notes button
- Made the recent changes to get saved if the user clicks creates a task before saving the changes.
- Added "No Notes Available if No Notes are available.
- Added "Create A Note" from the edit menu.
- Used PopUpHandlerService to Create A Task
- Used EventEmitter for toggling the AddNewTask
- Check if "No Notes Available" is shown when no notes are added.
- Add a note and click create a task and check whether the title and description are shown in the respective input fields of the Create new task modal.
- Do the same for the EditNote
- In the edit note component click on the + icon and check whether it takes to the add new note Component.
- Click create a task without saving the changes and check whether …
=> fix(QuickNotes-Menu):Added Create A Task

src/app/body/kanban-board/kanban-board.component.ts
Signed-off-by: sid-bagwe <siddhesh.ab@somaiya.edu>
Fixed the kanban board for first load
The selectedStatusLabels variable was not getting assigned with the value properly on first load.
Fixed the issue
ng serve
=> feat(dev/kanbanBoardFix): Fixed the kanban board

src/app/body/create-new-task/create-new-task.component.ts, src/environments/environment.ts
Project change should fetch particular team details after loader appears
Loader added to notify the user when project is switched from dropdown
Go to Create Task popup and switch between projects to see loader
=> fix(CreateNewTask): added loader upon project change

src/app/body/create-new-sprint/create-new-sprint.component.html, src/app/body/create-new-sprint/create-new-sprint.component.ts
fix (create new sprint reload):closing the popup without creating the spring, the whole page reloads
Changes in create-new-sprint-component
- [ x] low
clicking on create new sprint, and then closing the popup without creating the spring, the whole page is not reloading now
=> fix (create new sprint reload):closing the popup without creating the spring, the whole page reloads

src/app/body/view-organization-details/teams-card/teams-card.component.html
Speed images won't be overlapping in teams card
Changes in speed-images component
<-- steps for testing:
1. ng serve
2. firebase emulators:start
3. go to My Organisation.
4. then scroll down the page.
5. you can see the speed images won't be overlaping the footer.
6. bug fixed!
-->
=> fixed(speed-images):fixed the  allignment of speed images

src/app/body/create-new-team/create-new-team.component.ts
<--close button of create new team redirects to view organization details-->
<--changed the close function navigation from mydashboard to vieworganizationdetails -->
<--Steps to check the functionality
1. ng serve
2. firebase emulators:start
3. go to my organization
4. click on create new team icon
5. click on close button
6. will redirect to organization details instead of my dashboard. -->
=> Fix create new team popup

src/app/body/kanban-board/kanban-board.component.ts
on switching teams, the sprint number is not changing itself
Updated the sprint number in startservice
By changing the teamID
=> Fix/kanban board: fixed the filter

src/app/body/create-new-task/create-new-task.component.html
<--Sprint number button is removed from task creation succession popup -->
<--Added ngIf to hide the buttons from  task creation succession popup  -->
<-- Steps to test functionality/bug:
1. ng serve & firebase emulators:start
2. go to create new task
3. create task
4. active sprint button will not be displayed in task creation succession popup. -->
=> Fix create new task popup

src/app/body/kanban-board/kanban-board.component.ts
While switching teams more than once, and reloading the page, the whole layout changes
Emptied the array when function hits more than once
switch teams more than once, and then reload the page simultaneously
=> Fix(Kanban-board): fixed the reload

src/app/body/common-tools/data-table/data-table-datasource.ts, src/app/body/common-tools/data-table/data-table.component.html, src/app/body/my-dashboard/my-tasks/my-tasks.component.ts
Replaced the difficulty icon with current Sprint Number
Replaced the difficulty icon with sprint Number
Check the My dashboard page
=> fix/sprintNumber : Replaced the difficulty icon with current sprintNumber

src/app/body/view-organization-details/teams-card/teams-card.component.html
The gear icon in the my organisation page was not appearing at appropriate place when we were making any new team .
Fixed the gear icon
1. Go to my organisation page
2. Create a new team with task description.
=> fixed (gear icon) :Task details page

src/app/body/home/home.component.html, src/app/body/tasks-evaluation/tasks-evaluation.component.ts
Fixed the Upcoming sprint bucket on task evaluation page
When clicked on load more the upcoming sprint bucket was increasing. Fixed that
Try clicking on load more and check whether the upcoming sprint bucket is visible only once
=> Fixed upcoming sprint bucket on load more

src/app/body/filter-task/filter-task.component.html
Signed-off-by: RaunakSharma002 <raunaksharma22345@gmail.com>
custom task filter not getting selected
it is getting selected
Dev557
by going board then task and then select custom filter
=> Fix task filter

src/app/body/create-new-team/add-member/add-member.component.ts
Same Member email was added more than one time.
Now Unable to add same member more than one time
Go to Add members and try adding two emails same time.
=> Fixed:Add members

src/app/body/board/sprint-burndown-chart/sprint-burndown-chart.component.ts
Error before sprint burndown chart loading is replaced with a loader
Fixed the Initialization of showLoader variable
Dev601
Try Loading the boards page and check whether the error appears.
=> fix(charts):Fixed loaded in sprint burndown chart

src/app/body/board/sprint-details/sprint-details.component.ts
end Date format was not correct and workpercentage was not correct
make end Date in right format and workpercentage as 100% when status is completed
Dev634
going into board and changing sprint number
=> fix sprint details for previous sprint

src/app/header/login-handler/user-card/user-card.component.ts, src/app/services/theme/theme.service.ts
Fixed App theme after logout.
Changes in theme service and user-card component.
1.Open Emulator
2.Login and change the app theme from light to dark.
3.Logout
=> Fix(theme):Fixed App theme after logout

functions/model/milestone/lib.js, functions/model/milestone/milestone.js, functions/model/milestone/tark/deleteMilestone.js, src/app/Interface/MilestoneInterface.ts, src/app/body/milestone/milestone-card/milestone-card.component.css, src/app/body/milestone/milestone-card/milestone-card.component.html, src/app/body/milestone/milestone-card/milestone-card.component.ts
Added delete functionality
Changes in milestone-card component 
1.Open emulators
2.Go to milestones
3. Create Milestone
4. you can use delete functionality of milestones
=> Feat(milestone-card):Added delete functionality

src/app/body/kanban-board/kanban-board.component.ts
Upon drag the data change takes time to reflect as new data.
Improve implementation to update local data instantly, without waiting to update db
Dev667
Go into kanban board, drag and drop
=> Istant data set on kanban board
