Worktez/worktez

public/index.html, public/scripts/worktrollyUI.js
I have made create New task option in worktrolly which is fully responsive based on bootstrap4.
**How to test?**
`public/index.html`
After navbar, I have created createNewTask.
I have added material icons link at the end of the body tag.
`scripts/worktrollyUI.js`
I have added a jquery function to create hide and show options and created a date method.
**demo-image-link**
Go in the link to check how it looks like.
=> added create new task

public/index.html, public/scripts/worktrollyUI.js
I have added a sample card in worktrolly which shows a summarize information about create a new task form.
**How to test**
`index.html`
_Added_ 
A particular id to every input in createNewTask form which is required for the card.
UI of card 
`worktrollyUI.js`
Added a submitCreateNewTask function, inside this I have added a variable, console, and innerHTML code in jquery format.
=> cards added in worktrolly

functions/index.js, public/index.html, public/scripts/worktrollyUI.js
**Introduction**
Added create new task functions in worktrolly.
**Descriptions**
To store data in the firestore using cloud functions.
**How to Test**
added proper id in the HTML file.
added function in index.js
=> Dev/create new task functions - Sai bignesh

public/index.html, public/scripts/config.js, public/scripts/frames.js, public/scripts/framesFunction.js, public/scripts/worktrollyClassData.js, public/scripts/worktrollyUI.js
**Introduction**
Added Card Frames in worktrolly
Added card frames and it's working. The function take data from firestore and display as cards.
**How to test**
`config.js`
now I have added my configuration, so change it as official.
`frames.js`
added frames and its method
`framesFunction.js`
added working of frames and read method which read the data from firestore.
added object of a class.
`worktrollyClassData.js`
added class
=> Added frames

public/scripts/frames.js
Introduction
modified frames UI
Description
I have changes Ui as required, but now I have not added date and id.
How to test
In frames.js I have modified Frames UI
=> FramesUI modified

public/index.html, public/scripts/config.js, public/scripts/dashboard.js, public/scripts/frames.js, public/scripts/worktrollyUI.js
selecting specific category and display on newpage.
=> Filter task

functions/index.js, public/index.html, public/scripts/config.js, public/scripts/frames.js, public/scripts/worktrollyClassData.js, public/scripts/worktrollyUI.js
**Introduction**
Created card description
Created card description UI and then created functionality of the card description page.
**How To Test**
Created UI in index.html . Then created functionality in frames.js, created the API for card description in index.js .
=> feat(cardDescriptionPage)created UI and done functionality

functions/index.js, public/index.html, public/scripts/config.js, public/scripts/frames.js, public/scripts/worktrollyClassData.js, public/scripts/worktrollyUI.js
Introduction
Created  logWork
Description
Created  logWork UI and then created functionality of the  logWork page.
How To Test
Created UI in index.html . Then created functionality in frames.js, created the API for logWork in index.js .
=> feat(logWork):UI and functionality

functions/index.js, public/index.html, public/scripts/config.js, public/scripts/dashboard.js, public/scripts/worktrollyUI.js
From start new sprint if the counters are not available the show 0 as counter values.
Create the sprint counters at right time in code flow.
=> feat(counterUpdate): updated counter functionality

functions/index.js, public/index.html, public/scripts/config.js, public/scripts/dashboard.js, public/scripts/worktrollyUI.js
Reverts Worktrolly/worktrolly#33
=> Revert "feat(counterUpdate): updated counter functionality"

functions/index.js, public/index.html
**Introduction**
fixed counter bug in creating sprint and create new task And added logo in the title bar.
Added proper counter And logo
**How To Test**
index.js for counter functionality.
index.html for logo
=> fixed counter update

.github/pull_request_template.md
added template for pull request
=> Template for pull request

.github/pull_request_template.md
**Functionality:**
fixed pr template for better view
**Solution:**
changed the title from bold to heading
**Risk level:**
**How to test:**
raise pr to test
=> fix (template): fixed pull request template

public/backlogpatch.html, public/index.html, public/scripts/backlogpatch.js
move data from s-1 to backlog
created a function called setDataIntoBacklog that moves data from s-1 to backlog
While using this function ,please check the collection name
=> feat(dev/moveData) - created a patch the move data from s-1 to backlog

functions/index.js, public/index.html, public/scripts/worktrollyUI.js
added EditSprintCounter and solved marketing task counter bug
now we can change the sprint numbers in the edit task option and all the counter will update properly.
Added functionality in index.js inside Edit task functionality.
=> added EditSprintCounter and solved marketing task counter bug

database.rules.json, firebase.json, firestore.rules, package-lock.json
Signed-off-by: vivek kumar <vivekkumar@viveks-MacBook-Air-2.local>
Adding angular framework to wortrolly
It's difficult to follow norms and update the tool with the current flow and therefore we can use this branch for angular based project.
Follow angular
=> feat(angular): Adding angular to project

worktrolly-ui/firebase.json, worktrolly-ui/src/app/Interface/RawDataInterface.ts, worktrolly-ui/src/app/app-routing.module.ts, worktrolly-ui/src/app/app.module.ts, worktrolly-ui/src/app/body/dashboard/dashboard.component.html, worktrolly-ui/src/app/body/dashboard/dashboard.component.spec.ts, worktrolly-ui/src/app/body/dashboard/dashboard.component.ts, worktrolly-ui/src/app/body/dashboard/feature-card/feature-card.component.html, worktrolly-ui/src/app/body/dashboard/feature-card/feature-card.component.spec.ts, worktrolly-ui/src/app/body/dashboard/feature-card/feature-card.component.ts, worktrolly-ui/src/app/body/dashboard/sprint-details/sprint-details.component.html, worktrolly-ui/src/app/body/dashboard/sprint-details/sprint-details.component.spec.ts, worktrolly-ui/src/app/body/dashboard/sprint-details/sprint-details.component.ts
Signed-off-by: vivek kumar <vivekkumar@viveks-MacBook-Air-2.local>
Updated dashboard component in angular
Added component and sub component
ng serve
=> feat(angular): Updated Dashboard component

public/index.html, public/scripts/dashboard.js, public/scripts/worktrollyUI.js
Added a button 
Added button called current sprint in  dashboard.
- [x ] low
By clicking on the current sprint button , you will be taken to the current sprint .
=> feat(currentSprint):current sprint showing in dashboard

functions/index.js, public/index.html, public/scripts/worktrollyUI.js
Signed-off-by: sandeep-v1404 <valpasanisandeep@gmail.com>
Implemented Validation in **LogWork Form** , **CreateNewSprint Form**  , **EditTask Form** and **CreateNewTask Form** 
Added the functionality by using **Bootstrap Forms**
While creating a new Task or Sprint , Logging the Work or Editing the Task , by **mistake** if any input value is not entered and clicked on **Submit** button , it intimates the user to **enter** that particular value .It submits only after all values are entered Correctly . By this validation , the Log Hour Bug will be fixed .
=> feat(logWorkForm):Validation in logWork,sprint,Edit,newTask

functions/index.js, worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.ts, worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.html, worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.ts, worktrolly-ui/src/app/body/task-details/task-details.component.html, worktrolly-ui/src/app/body/task-details/task-details.component.ts
1.Counters ,
2.Update Task Details using SnapshotChanges
1.To make Counters work , bugs are fixed with Promises in logWork , editPageTask , deleteTask Cloud Functions . 
2. Task Details will be Updated asynchronously.
1.ng serve 
2.Try to Edit Task and Delete a Task .
3.Log a Task with Status "Completed" , Then checkout the Task Detail Page . 
4.Task Details will be updated after Editing or Logging the Task .
=> feat(TaskDetail):Fixed details of Task using Snapshot Changes

worktrolly-ui/src/app/body/create-new-session/create-new-session.component.html, worktrolly-ui/src/app/body/dashboard/dashboard.component.html, worktrolly-ui/src/app/body/dashboard/dashboard.component.ts
Shows the current sprint.
To make the button align with backlog button
By clicking the button it will take you to the current sprint.
=> feat(currentSprintButton):added sprint button and its functionality

worktrolly-ui/src/app/app.module.ts, worktrolly-ui/src/app/body/create-new-session/create-new-session.component.html, worktrolly-ui/src/app/body/create-new-session/create-new-session.component.ts, worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.html, worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.ts, worktrolly-ui/src/app/body/dashboard/dashboard.component.html, worktrolly-ui/src/app/body/loader/loader.component.css, worktrolly-ui/src/app/body/loader/loader.component.html, worktrolly-ui/src/app/body/loader/loader.component.spec.ts, worktrolly-ui/src/app/body/loader/loader.component.ts, worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.html, worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.ts, worktrolly-ui/src/app/body/task-details/log-work/log-work.component.html, worktrolly-ui/src/app/body/task-details/log-work/log-work.component.ts, worktrolly-ui/src/app/body/task-details/task-details.component.html, worktrolly-ui/src/app/body/tasks/tasks.component.html
Signed-off-by: sandeep-v1404 <valpasanisandeep@gmail.com>
Added Loader to all Pages
To create a Loader Component
1. ng serve
2. Dashboard , Tasks ,TaskDetails Contains a Loader
3. Loader after Clicking Submit in CreateNewTask ,CreateNewSprint ,EditTask ,LogWork
=> feat(Loader):Added Loader in All pages

worktrolly-ui/src/app/icons/priority-icons/priority-icons.component.html, worktrolly-ui/src/app/icons/status-icons/status-icons.component.html
Signed-off-by: sandeep-v1404 <valpasanisandeep@gmail.com>
Typo fix in Icon Components. 
Replace ng-Container with ng-container tag
ng serve
=> feat(IconComponent):Replaced ng-Container with ng-container tag

worktrolly-ui/src/app/body/task-details/task-details.component.css, worktrolly-ui/src/app/body/task-details/task-details.component.html
Move Edit and Log work button to submenu bar
added icon to the edit button and moved them to the submenu bar
ng serve
go to the task section and open any task
=> Edit logwork btn

functions/addActivity.js, functions/createNewTaskAPI.js, functions/createNewUserAPI.js, functions/deleteTaskAPI.js, functions/editPageTaskAPI.js, functions/logWorkAPI.js, functions/startNewSprintAPI.js
User should be able to Create, Log, Edit and Delete Tasks with Activity Tracking. 
Fixed the API with AddActivity Function.
- **firebase emulators:start** in **worktrolly** directory
- **ng serve** in **worktrolly-ui** directory
- Log In
- Observe FirestoreDB, you will notice User,RawData Collection
- Create Task, check FirestoreDB.
- Similarly Edit, Log and Delete Task.
- Observe Activity Collection.
- Have a look around Counters in Main, RawData Collection.
- This will even work with Tasks which are created in Previous Sprints.
=> feat(API) : Fixed Activity with promises

src/app/body/board/sprint-details/sprint-details.component.html
Reverts Worktrolly/worktrolly#126: Merged to master
=> Revert "feat(sprint-details): Deleted Sprint Details"

src/app/body/board/sprint-details/sprint-details.component.css, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/board/sprint-details/sprint-details.component.ts
Sprint detail UI
Removed space between filter and status button and also created status dropdown 
ng serve
=> feat(sprinttUI):UI changes of sprint details

functions/addUserEmailAPI.js, functions/createNewOrgAPI.js, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/user-verification/user-verification.component.css, src/app/user-verification/user-verification.component.html, src/app/user-verification/user-verification.component.spec.ts, src/app/user-verification/user-verification.component.ts
user varification through mail
Mail is sent to all the members to verify user authenticate.
firebase deploy
=> feat(userVerification): user verify email API

functions/patchAPI.js, src/app/patch/patch.component.html, src/app/patch/patch.component.ts
Moves tasks to new database structure
Made a patch to do it
Open the patch, 
Enter the Organization ID and the set all other values to 0 and click the button to run the patch.
=> Made a patch to move tasks to new structure

functions/addActivity.js, functions/createNewTaskAPI.js, functions/deleteTaskAPI.js, functions/editPageTaskAPI.js, functions/logWorkAPI.js, src/app/Interface/ActivityInterface.ts, src/app/body/task-details/task-details.component.css, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts
updated activity API and added activityTab in task des
Updated activity API according to organization and added activityTab in task description
ng serve
=> feat(activity): updated activity API and added activityTab in task des

functions/editPageTaskAPI.js, functions/logWorkAPI.js, src/app/body/board/board.component.ts
Fixed Sprint filter and edit task page.
Fixed edit and log work api's,
Fixed sprint filter functionality.
Check by editing the task.
Check by logging the work.
Check by changing the sprint using the filter.
=> Fixed Sprint Filter and edit task page

src/app/app.module.ts, src/app/body/common-tools/time-chart/time-chart/time-chart.component.html, src/app/body/common-tools/time-chart/time-chart/time-chart.component.spec.ts, src/app/body/common-tools/time-chart/time-chart/time-chart.component.ts, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts
Signed-off-by: RohitVarma001 <arv032000@gmail.com>
Showing remaining time and logged time in bar chart
Time-chart component which takes log data and shows remaining and log time in bar chart 
enter `firebase emulators: start`
enter `ng serve`
=> feat(time-remaining-graph):added time remaining graph to task details

functions/index.js, src/app/Interface/TasksInterface.ts, src/app/body/create-new-session/create-new-session.component.html, src/app/body/create-new-session/create-new-session.component.ts, src/app/body/filter-task/filter-task.component.html, src/app/body/filter-task/filter-task.component.ts, src/app/body/task-details/edit-page/edit-page.component.html, src/app/body/task-details/edit-page/edit-page.component.ts, src/app/body/task-details/task-details.component.ts, src/app/body/tasks/tasks.component.html, src/app/body/tasks/tasks.component.ts, src/app/services/application-settings.service.ts, src/app/services/validation.service.ts
migrated category to project
migrated category to project from everywhere in UI
ng serve
=> feat(migrateCategoryToProject): changed Category to Project

src/app/body/my-dashboard/performance-chart/performance-chart.component.ts
Due to change in DB, Performance graph is not working
Bug Fixed and Code Updated
1. ng serve
2.  firebase emulators:start
=> (feat) performanceChart bugFix

functions/createNewOrgAPI.js, functions/createNewTaskAPI.js, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/body/body.component.html, src/app/body/body.component.ts, src/app/body/create-new-organization/organization-details/organization-details.component.ts, src/app/body/setup/setup.component.html, src/app/body/setup/setup.component.spec.ts, src/app/body/setup/setup.component.ts, src/app/header/header.component.html
Makes an organization, 2 teams, a sprint, and a few tasks for the developer when they start the emulator.
Made a setup component which calls all APIs necessary to create the needed
1. ng serve
2. firebase emulators:start
3. Create a new user
4. Refresh
5. Login again
6. Click on the Auto Setup button 
7. Modify the user with the organization AppKey manually
8. Start the development process with a pre-made set of tasks and teams and sprints!
=> Made the setup patch for developers

src/app/body/tasks/task-cards/task-cards.component.css, src/app/body/tasks/task-cards/task-cards.component.html, src/app/body/tasks/tasks.component.css, src/app/body/tasks/tasks.component.html, src/app/body/tasks/tasks.component.ts
Signed-off-by: Akshay-Jak <akshayjani2147@gmail.com>
Added headings for task page above task cards
Added the headings in task component above task card
ng serve
Go to tasks page
=> Made Headings for Task page

src/app/body/board/board.component.ts, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/board/sprint-details/sprint-details.component.ts
Add menu option , that helps to navigate to 
- Active Sprint
- Backlog
- Deleted Task
A dropdown menu added to the board that consists of sprint details
1. ng serve
2. firebase emulators:start
=> Menu(feat):Adding menu option in sprint details on the board

functions/createNewOrgAPI.js, functions/createNewTaskAPI.js, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/body/board/board.component.ts, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/board/sprint-details/sprint-details.component.ts, src/app/body/body.component.html, src/app/body/body.component.ts, src/app/body/create-new-organization/organization-details/organization-details.component.ts, src/app/body/setup/setup.component.html, src/app/body/setup/setup.component.spec.ts, src/app/body/setup/setup.component.ts, src/app/body/tasks/task-cards/task-cards.component.css, src/app/body/tasks/task-cards/task-cards.component.html, src/app/body/tasks/tasks.component.css, src/app/body/tasks/tasks.component.html, src/app/body/tasks/tasks.component.ts, src/app/header/header.component.html
1. Given heading to task page.
2. Converted task page to tables.
3. Added menu option to sprint dashboard.
4. Added quick setup for emulator support.
in real site.
=> Internal Release 1.4

functions/verifyUserAPI.js, src/app/body/login/login.component.ts, src/app/header/login-handler/login-handler.component.html
User email can now be verified using the link received in the mail.  
Made changes to the login component to route the user to verification page after login when necessary
ng serve
=> feat(verifyEmail): Fixed verify user Email

src/app/app.module.ts, src/app/body/common-tools/pie-chart/pie-chart.component.html, src/app/body/common-tools/pie-chart/pie-chart.component.spec.ts, src/app/body/common-tools/pie-chart/pie-chart.component.ts, src/app/body/tasks/task-cards/task-cards.component.html, src/app/body/tasks/work-completion/work-completion.component.html, src/app/body/tasks/work-completion/work-completion.component.spec.ts, src/app/body/tasks/work-completion/work-completion.component.ts
Signed-off-by: Kanishk6677 <kanishkraj6677@gmail.com>
Implemented Work Completion Graph for a given particular task
Used ng circle session charts to demonstrate the work done by passing the data of workdone
ng serve
firebase emulators: start
=> feat():implementation of  workcompletion graph completed

src/app/body/create-new-session/create-new-session.component.html, src/app/body/create-new-session/create-new-session.component.ts, src/app/services/backend.service.ts
Added  People-Suggestion functionality to Create New Task Component
Used Application Setting Service to get Team Member details.
`firebase emulators:start`
`ng serve`
=> feat(People-Suggestion):Added list of TeamMembers to AssigneeName

src/app/body/task-details/task-details.component.css, src/app/body/task-details/task-details.component.html
Completion date is not shown in task details and now is visible in the activity area
Removed the completion date and made changes in the look
ng serve
View any task detail page
Pictures:
=> Removed the Completion date from UI

src/app/body/profile/profile.component.ts, src/app/body/tasks/tasks.component.ts
Profile and tasks pages were not working correctly when accessed directly using the link.
Fetched the user data required similar to as it is done in tasks details component.
Try Accessing the profile page and tasks page directly by putting the link in the browser.
=> feat(fixes): Fixed profile and tasks page

src/app/body/my-dashboard/my-dashboard.component.html, src/app/body/my-dashboard/my-dashboard.component.ts, src/app/body/my-dashboard/my-tasks/my-tasks.component.ts, src/app/body/my-dashboard/performance-chart/performance-chart.component.ts, src/app/body/setup/setup.component.ts
Signed-off-by: RohitVarma001 <arv032000@gmail.com>
Change Querying with User Name to User Email
Changed All places where we querying  with User Name to User Email
1. `firebase emulators:start`
2. `ng serve`
=> Fix:Update all quering from userName to userEmail

src/app/body/task-details/edit-page/edit-page.component.html, src/app/body/task-details/edit-page/edit-page.component.ts
Added the Assignee Solution
Added the datalist in edit page component
ng serve
=> Assignee sugg

functions/model/patch/patch1.js, src/app/body/body.component.html, src/app/body/body.component.ts, src/app/body/create-new-sprint/create-new-sprint.component.html, src/app/body/create-new-sprint/create-new-sprint.component.ts, src/app/body/home/home.component.ts, src/app/body/my-dashboard/performance-chart/performance-chart.component.ts, src/app/body/task-details/edit-page/edit-page.component.html, src/app/body/task-details/edit-page/edit-page.component.ts, src/app/patches/patch3/update-field/update-field.component.ts, src/app/services/tool/tools.service.ts
Release 2.1(I-beta)
1. Added the Assignee Suggestion
2. Fixed the bug for Patch3 API call
3. Fixed bugs in create new sprint component
4. Fixed the bug in Patch1
5. Fixed bug for infinite loading in Home Page
6. Fixed bug for loading empty page on Home Page
In release 2.1
=> Internal Release 2.1

src/app/body/task-details/task-details.component.css, src/app/header/header.component.html, src/app/header/header.component.ts
fixed description bug and redirected logo to home
fixed description bug and redirected logo to home
ng serve
=> feat(dev/update) fixed description bug and redirected logo to home

src/app/body/task-details/edit-page/edit-page.component.ts
Signed-off-by: RohitVarma001 <arv032000@gmail.com>
Error in submitting edit page
Solved error in assignee name
1. `firebase emulators:start`
2. `ng serve`
=> Fix(edit-page):Submission of Edit Page

src/app/body/create-new-organization/create-new-organization.component.html, src/app/body/create-new-organization/organization-details/organization-details.component.css, src/app/body/create-new-organization/organization-details/organization-details.component.html, src/app/body/create-new-organization/organization-details/organization-details.component.ts, src/app/body/create-new-organization/team-details/team-details.component.css, src/app/body/create-new-organization/team-details/team-details.component.html, src/app/body/create-new-organization/team-details/team-details.component.ts
The navbar now relates to the content of the TeamDetails form
It also has a close button now
Added some ng containers and if statements
ng serve
Try creating an organization and then update it
=> feat(TeamDetails Page): Make navebar powerful

src/app/body/task-details/task-details.component.ts
Reopen icon
Fixed the reopen task bug
ng serve
=> feat(dev/reopen): fixed reopen task bug

src/app/body/body.component.css, src/app/body/body.component.html, src/app/body/task-details/log-work/log-work.component.html, src/app/body/task-details/log-work/log-work.component.ts, src/app/footer/footer.component.css, src/app/footer/footer.component.html
Signed-off-by: Murlidhar Pathak <murlidharpathakprogrammer>
Automated status and work completion input field in logwork.
Automated input fields
ng serve --open
=> feat(Automated the data in Logwork and added non-editable userID)

functions/model/email/lib.js, src/app/app.component.css, src/app/body/board/sprint-details/sprint-details.component.css, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/create-new-organization/create-new-organization.component.css, src/app/body/create-new-organization/organization-details/organization-details.component.css, src/app/body/create-new-organization/team-details/add-member/add-member.component.css, src/app/body/create-new-organization/team-details/team-details.component.css, src/app/body/create-new-organization/team-details/team-details.component.html, src/app/body/create-new-session/create-new-session.component.css, src/app/body/create-new-session/create-new-session.component.html, src/app/body/create-new-sprint/create-new-sprint.component.css, src/app/body/create-new-sprint/create-new-sprint.component.html, src/app/body/login/login.component.css, src/app/body/navbar/navbar.component.css, src/app/body/profile/edit-profile/edit-profile.component.html, src/app/body/profile/profile.component.html, src/app/body/task-details/edit-page/edit-page.component.css, src/app/body/task-details/log-work/log-work.component.css, src/app/header/header.component.css, src/app/header/login-handler/login-handler.component.css
Fix for the UI changes.
Changed the css files to match the existing UI.
ng serve
=> feat(UI Fixes)

src/app/app.module.ts, src/app/body/common-tools/warning/warning.component.css, src/app/body/common-tools/warning/warning.component.html, src/app/body/common-tools/warning/warning.component.spec.ts, src/app/body/common-tools/warning/warning.component.ts, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts
Added a Warning Page before deleting a Task.
Made a Warning Component.
ng serve --open
=> feat(dev/Warning-Page): Made Warning-Page.

src/app/Interface/OrganizationInterface.ts, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/body/view-organization-details/view-organization-details.component.css, src/app/body/view-organization-details/view-organization-details.component.html, src/app/body/view-organization-details/view-organization-details.component.spec.ts, src/app/body/view-organization-details/view-organization-details.component.ts, src/app/header/header.component.css, src/app/header/header.component.html, src/app/header/header.component.ts
Signed-off-by: sid-bagwe <siddhesh.ab@somaiya.edu>
Made an organization page.
Created a new component in the body and displayed all the required data of the organization and teams and also added the create team, update team and add team members feature there.
ng serve
=> feat(organizationPage): Created an Organization Page

src/app/app.module.ts, src/app/body/tasks/task-cards/task-cards.component.html, src/app/icons/difficulty-icons/difficulty-icons.component.css, src/app/icons/difficulty-icons/difficulty-icons.component.html, src/app/icons/difficulty-icons/difficulty-icons.component.spec.ts, src/app/icons/difficulty-icons/difficulty-icons.component.ts, src/environments/environment.ts
Added Difficulty icons in task card.
Added difficulty icon Component in icons folder.
ng serve 
=> feat(dev/addDifficulty-icons):added difficulty-icons in task card

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, LICENSE.md
Updated issue templates - Bug report and Feature request.
=> Update issue templates

src/app/body/create-new-organization/team-details/add-member/add-member.component.ts
Enabled adding members while creating new organization
Getting OrgDomain from backend service only if organization exists
Create a new organization,
Add member
=> feat(dev/members): fixed adding members

src/app/body/create-new-session/create-new-session.component.ts, src/app/body/task-details/edit-page/edit-page.component.ts, src/app/services/tool/tools.service.ts, src/app/services/validation/validation.service.ts
Create new task email input
Let's user give an email that is not present in datalist too.
ng serve
=> feat(dev/Assignee) : create new task bug

functions/model/patch/editPatch.js, src/app/app.module.ts, src/app/list-patches/add-patch/add-patch.component.css, src/app/list-patches/add-patch/add-patch.component.html, src/app/list-patches/add-patch/add-patch.component.spec.ts, src/app/list-patches/add-patch/add-patch.component.ts, src/app/list-patches/edit-patch/edit-patch.component.ts, src/app/list-patches/list-patches.component.css, src/app/list-patches/list-patches.component.html, src/app/list-patches/list-patches.component.ts
Add Patches to List Patches page
Created a component, addPatch and used patchModerator to addPatch to db.
ng serve
go to /ListPatches in route.
=> feat(AddPatch): Add Patch feature

src/app/body/task-details/task-details.component.css, src/app/body/task-details/task-details.component.html
Task Activity Component's Dark theme is fixed.
No Activity description wasn't visible, fixed that also.
Added border and background color.
firebase emulators:start 
ng serve --start
=> fixed dark theme UI of Categorize Tab Task.

functions/model/tasks/getTaskDetails.js, functions/model/tasks/tasks.js, src/app/body/task-details/task-details.component.ts
Fetch and display task details
Used API to fetch.
ng serve
firebase emulators: start
=> (Dev/task): Fetched task details using API

functions/model/patch/patch2.js, src/app/patches/patch1/patch1.component.html, src/app/patches/patch2/patch2.component.html, src/app/patches/patch2/patch2.component.ts, src/app/patches/patch3/patch3.component.html, src/app/patches/patch4/patch4.component.html, src/app/patches/patch5/patch5.component.ts
Patch2 can now add empty array instead of only string & Patch 5 loader bug fixed
Added choice of field in patch2 and kept showLoader false in patch5 components
ng serve 
Go to /Patch5 and run
Go to /Patch2 and select the NewFireldValueType and give neccesary values and run
=> Patch5 BugFix

src/app/body/board/board.component.html, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/board/sprint-evaluation-graph/sprint-evaluation-graph.component.css, src/app/body/board/sprint-evaluation-graph/sprint-evaluation-graph.component.html, src/app/body/common-tools/show-files/show-files.component.html
Bug Fixes
Fixed bugs in  Sprint Filter, File download and Sprint Evaluation Graph
2. ng serve
3. Change sprint using filter
4. Download an uploaded file
5. View Sprint Evaluation Graph in Board page
=> (feat/fixes):SprintEvalGraph-Filter-FileDownload

src/app/body/board/performance-column-chart/performance-column-chart.component.html, src/app/body/board/performance-column-chart/select-dropdown/select-dropdown.component.html, src/app/body/create-new-sprint/create-new-sprint.component.html, src/app/body/create-new-task/create-new-task.component.html, src/app/body/create-new-team/add-member/add-member.component.html, src/app/body/create-new-team/create-new-team.component.html, src/app/body/my-dashboard/performance-chart/range-card/range-card.component.html, src/app/body/profile/edit-profile/edit-profile.component.html, src/app/body/profile/profile.component.html, src/app/body/task-details/edit-page/edit-page.component.html, src/app/body/task-details/log-work/log-work.component.html, src/app/body/tasks-evaluation/tasks-evaluation.component.html, src/app/body/tasks/tasks.component.html, src/app/body/view-organization-details/teams-card/teams-card.component.html, src/app/body/view-organization-details/view-organization-details.component.html
fixing headers
changed heading tags wherever required 
ng serve
=> changed heading tags

src/app/body/board/board.component.html, src/app/body/board/board.component.ts, src/app/body/board/sprint-evaluation-graph/sprint-evaluation-graph.component.html, src/app/body/my-dashboard/performance-chart/range-card/range-card.component.html
Fixed Sprint Evaluation Graph
Added condition in order to send valid inputs to Sprint Evaluation Graph
2. ng serve
=> (fix/sprintEvalGraph): fixed sprintEvaluationGraph

src/app/body/filter-task/filter-task.component.css, src/app/body/filter-task/filter-task.component.html, src/app/body/filter-task/filter-task.component.ts, src/app/body/tasks/tasks.component.css, src/app/body/tasks/tasks.component.html, src/app/body/tasks/tasks.component.ts, src/app/services/applicationSettings/application-settings.service.ts, src/app/services/filter-task/filter-task.service.spec.ts, src/app/services/filter-task/filter-task.service.ts
Updated filter button on tasks page
Grouped sprint and other filter options together.
ng serve
=> (dev/task): Updated filter button in tasks

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/body/copyright/copyright.component.css, src/app/body/copyright/copyright.component.html, src/app/body/copyright/copyright.component.spec.ts, src/app/body/copyright/copyright.component.ts, src/app/footer/footer.component.html, src/app/footer/footer.component.ts
Added copyright component
added copyright component and setup app route for the component, then added content in the html file
in footer, click on copyright.
=> feat(copyright) added copyright component

functions/model/teams/createTeam.js, functions/model/teams/deleteTeam.js, functions/model/teams/lib.js, functions/model/teams/teams.js, functions/model/teams/updateTeam.js, src/app/Interface/TeamInterface.ts, src/app/body/body.component.html, src/app/body/view-organization-details/teams-card/teams-card.component.html, src/app/body/view-organization-details/teams-card/teams-card.component.ts
Delete team
added a delete team feature that deletes teams only from UI.
ng serve
=> (dev/deleteTeam) : added delete team feature

src/app/body/create-new-team/add-member/add-member.component.css, src/app/body/create-new-team/add-member/add-member.component.html, src/app/body/view-organization-details/teams-card/teams-card.component.css, src/app/body/view-organization-details/teams-card/teams-card.component.html, src/app/body/view-organization-details/view-organization-details.component.css, src/app/body/view-organization-details/view-organization-details.component.html, src/app/body/view-organization-details/view-organization-details.component.ts, src/app/icons/profile-icons/profile-icons.component.css, src/app/icons/profile-icons/profile-icons.component.html
Ui migrated in organization details page
Used bootstrap to make the ui look like the prototype made in adobe xd
ng serve
Do the auto setup and then view the my organization page
=> feat(ui-migration): Migrated my organization page and add teams model

functions/.eslintrc.js, functions/model/application/lib.js, functions/model/performanceChart/getPerformanceChartData.js, functions/model/performanceChart/getSprintEvaluationGraph.js, functions/model/performanceChart/getUserPerformanceChartData.js, functions/model/performanceChart/updateSprintEvaluationGraph.js, functions/model/teams/lib.js
Fixed working of charts
Setting collection documents and LastUpdated variable when document doesn't exist
In intermediate release
=> fix(release 3.5i): Fixed working of charts

functions/.eslintrc.js, functions/model/application/lib.js, functions/model/performanceChart/getPerformanceChartData.js, functions/model/performanceChart/getSprintEvaluationGraph.js, functions/model/performanceChart/getUserPerformanceChartData.js, functions/model/performanceChart/updateSprintEvaluationGraph.js, functions/model/teams/lib.js
Release 3.5.1(I-beta)
Fixed working of charts
In release i3.5.1
=> Intermediate Internal Release 3.5.1

functions/model/patch/patch.js, functions/model/patch/patch9.js, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/body/setup/setup.component.ts, src/app/patches/patch9/patch9.component.css, src/app/patches/patch9/patch9.component.html, src/app/patches/patch9/patch9.component.spec.ts, src/app/patches/patch9/patch9.component.ts
Added Patch 9 to update field and value in users column
Added Patch 9
Check in route patch 9
=> feat(patch9): Added Patch 9

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/footer/footer.component.html, src/app/footer/footer.component.ts, src/app/terms-and-condition/terms-and-condition.component.css, src/app/terms-and-condition/terms-and-condition.component.html, src/app/terms-and-condition/terms-and-condition.component.spec.ts, src/app/terms-and-condition/terms-and-condition.component.ts
Signed-off-by: Abhishek Mishra <am1426620@gmail.com>
added terms and conditions component
added terms and conditions component for the footer and setup app route for the component, then added content in the html file.
in footer click "Terms
"
=> feat(terms and conditions): added terms and condtions component

functions/model/tasks/editTask.js, src/app/body/task-details/edit-page/edit-page.component.html, src/app/body/task-details/edit-page/edit-page.component.ts
Made Task Title and Status editable
In the edit-page component the title and status of the task can be edited
ng serve 
=> feat(edit-page): Made task title and status editable

functions/model/patch/patch.js, functions/model/patch/tark/patch10.js, functions/model/patch/tark/setPatches.js, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/body/setup/setup.component.ts, src/app/patches/patch10/patch10.component.css, src/app/patches/patch10/patch10.component.html, src/app/patches/patch10/patch10.component.spec.ts, src/app/patches/patch10/patch10.component.ts
patch10
patch10 allows users to add new fields to my organization collection.
ng serve
=> (dev/patch10): added patch10

functions/model/tasks/tasks.js, src/app/app.component.css, src/app/body/body.component.css, src/app/body/setup/setup.component.ts, src/app/body/task-details/task-details.component.html, src/index.html
Added link to the footer 
<span class="p-2" onclick="window.location='https://github.com/Worktez/worktez'">Contribute</span>
=> Add link to footer

src/app/body/common-tools/bar-chart/bar-chart.component.ts
Enhanced Velocity Chart
changed the colors of the bars in velocity chart
2. ng serve
3. auto setup
4. Go to board page. Observe the velocity chart.
=> velocity-colors: changed colors i velocity chart

functions/model/librarian/lib.js, functions/model/librarian/librarian.js, functions/model/librarian/tark/uploadUserProfilePic.js, functions/model/users/lib.js, functions/model/users/tark/updateProfilePic.js, functions/model/users/users.js, package-lock.json, package.json, src/app/app.component.html, src/app/app.module.ts, src/app/body/common-tools/update-image/update-image.component.css, src/app/body/common-tools/update-image/update-image.component.html, src/app/body/common-tools/update-image/update-image.component.spec.ts, src/app/body/common-tools/update-image/update-image.component.ts, src/app/body/profile/edit-profile-pic/edit-profile-pic.component.css, src/app/body/profile/edit-profile-pic/edit-profile-pic.component.html, src/app/body/profile/edit-profile-pic/edit-profile-pic.component.spec.ts, src/app/body/profile/edit-profile-pic/edit-profile-pic.component.ts, src/app/body/profile/edit-workexperience/edit-workexperience.component.ts, src/app/body/profile/profile.component.html, src/app/body/profile/profile.component.ts, src/app/services/fileUploadService/file-upload.service.ts
Users can now change their profile pictures
Used Cropper.js to be able to crop the photo
ng serve
Create a user and update the profile pic from profile page
=> feat(Feature): Allow user to update Profile Picture

src/app/body/task-details/task-details.component.ts
fix/dataUpdate
get data from backend and reload it after work is logged successfully
- [ x] low
2. ng serve
3. auto setup
4. select the task to be updated. The TaskDetails page opens.
5. Click on the log work icon on the Task Details component and log the work.
6. After the work is logged successfully, clicking on the close button updates the data.
=> fix/dataUpdate: reload data after work is logged successfully

src/app/body/board/performance-column-chart/performance-column-chart.component.ts, src/app/body/board/sprint-evaluation-graph/sprint-evaluation-graph.component.ts, src/app/body/my-dashboard/performance-chart/performance-chart.component.ts
Charts
sorted the charts sprint data 
ng serve
=> feat(dev/charts): sorted the charts data

src/app/body/create-new-task/create-new-task.component.html
fix CreateNewTask UI
Fix the UI of create new task and make the options more understandable
- [] low
2. ng serve
3. auto setup
4. click on the create button on the navbar and observe the changes
=> fix/CreateNewTaskUI: make options more understandable

src/app/body/create-new-task/create-new-task.component.css, src/app/body/create-new-task/create-new-task.component.html
Ui Fix
Fixed the padding issue
ng serve
firebase:emulators:start
=> (UI Fix): Fixed create new task UI

src/app/body/create-new-task/create-new-task.component.css, src/app/body/create-new-task/create-new-task.component.html
Release 4.0.1(I-beta)
1. Fixed Create new task UI
In release i4.0.1
=> Intermediate Internal Release 4.0.1

src/app/body/create-new-task/create-new-task.component.html, src/app/body/create-new-task/create-new-task.component.ts
Made task type selectable in create new task
Used "select" input element to make it selectable.
ng serve
Check Create new task modal
=> feat(selectableTaskType): Made task type selectable in create new task

src/app/body/common-tools/show-files/show-files.component.html
feat/openFiles
open files in new tab upon click in Task details and My Organisation documents section.
2. ng serve
3. auto setup
4. go to my organisations document section. Upload a file if not one is uploaded.
5. click on the document icon of the respective file to view it. The file opens in a new tab.
=> feat/openFiles: open files upon click in task details and my organisations document section

functions/model/users/lib.js, functions/model/users/tark/getUserByUid.js, functions/model/users/users.js, src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.html, src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.ts, src/app/body/task-details/activity/activity.component.html, src/app/body/task-details/activity/activity.component.ts, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts, src/app/body/tasks/tasks.component.ts, src/app/services/user-service/user-service.service.ts
Improved User Service Logic
Improved User Service Logic, Needs testing with real deployment
Not tested yet
=> feat(UserServiceLogic): Improved user data reading mechanism

functions/model/teams/tark/updateTeam.js, src/app/body/create-new-team/add-member/add-member.component.ts, src/app/body/create-new-team/create-new-team.component.ts
Fixed Update Team Feature
Fixed the bug in updateTeam API 
Fixed the UI functionality of add-member while updating the team
Team Manager email also gets updated now
ng serve
Auto setup and try updating team details.
=> feat(updateTeamFix): Fixed Update Team Feature

src/app/body/body.component.html
Removed Quick Notes from Home page
Used ngif to check whether the user is logged in or not
Start the application , 
- Check whether quick notes button is visible before Logging in (It should not be visible).
- After logging in check whether the Add Notes Button is visible and working
=> fix(QuickNotes) : Remove Quick Notes from Home Page

functions/model/librarian/lib.js, functions/model/librarian/librarian.js, functions/model/librarian/tark/deleteFilesInOrg.js, src/app/Interface/FileInterface.ts, src/app/body/view-organization-details/org-documents/org-documents.component.ts, src/app/services/fileUploadService/file-upload.service.ts
Files can be deleted from documents 
added a seperate js file for deletion in api 
added seperate methods for orgDocument deletion.
1) ng serve -o
2) firebase emulators:start
3) My Organization
4) Upload Documents
5) Delete Document
=> fix(deleteFiles): fixed delete files

functions/model/performanceChart/tark/getSprintEvaluationGraph.js
limited the velocity-chart data 
made changes in the Api
limited the data being extracted
1) ng serve -o
2) firebase emulators:start
3) Sprint Evaluation Graph
=> fix(velocity-chart): limited velocityChart data

functions/index.js, functions/model/scheduledFunctions/scheduledFn.js, functions/model/scheduledFunctions/tark/startSchedular.js, functions/model/sprints/tark/updateAutoSprintStatus.js, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/board/sprint-details/sprint-details.component.ts, src/app/body/my-dashboard/my-dashboard.component.ts
To auto complete sprints when ending date is over
Schedulers are used to schedule a sprint 
Click on the dropdown from Menu in board page to start the scheduler. It will update automatically to check if the status has to be marked completed.
=> feat(DevSprintAutocompleteTask): autocomplete sprints

functions/model/performanceChart/tark/getPerformanceChartData.js
Made the performance chart filter work  
fixes done in the api by making the individual member data available for display 
ng serve
check performace chart filter
select different mail id's and check the individual user data
=> fix(performanceChart): Fixed the performace chart

functions/model/tasks/tark/createTask.js
Linker module
Link two tasks
Click on the create subtask button and fill details similar to creating a task
=> Fix link task

src/app/body/profile/edit-education/edit-education.component.ts, src/app/body/profile/edit-projects/edit-projects.component.ts, src/app/body/profile/edit-skills/edit-skills.component.ts, src/app/body/profile/edit-workexperience/edit-workexperience.component.ts, src/app/services/validation/validation.service.ts
Validation of newly added field in profile page
Adding validation service in profile page 
In Education,work experience,projects and skill ,without adding info if we click on submit it is showing validation error
=> fix(profile page):Validation of newly added field in profile page

src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts, src/app/icons/status-icons/status-icons.component.html
Made status icon visible in task details page and fixed the reload issue in reopening task.
Changed the typo in status-icons component 
Check whether the status icons are visible in task details page and check whether the page is updates automatically after reopening a task.
=> fix(statusicon):fixed status-icon,reload-issue

functions/model/tasks/lib.js, functions/model/tasks/tark/addComment.js, functions/model/tasks/tark/createTask.js, functions/model/tasks/tark/editTask.js, functions/model/tasksEvaluation/tark/readTasksEvalulationData.js, src/app/Interface/TasksInterface.ts, src/app/app.module.ts, src/app/body/body.component.ts, src/app/body/create-new-task/create-new-task.component.html, src/app/body/profile/edit-education/edit-education.component.ts, src/app/body/profile/edit-projects/edit-projects.component.ts, src/app/body/profile/edit-skills/edit-skills.component.ts, src/app/body/profile/edit-workexperience/edit-workexperience.component.ts, src/app/body/setup/setup.component.ts, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts, src/app/body/tasks-evaluation/tasks-evaluation.component.css, src/app/body/tasks-evaluation/tasks-evaluation.component.html, src/app/body/tasks-evaluation/tasks-evaluation.component.ts, src/app/header/header.component.html, src/app/header/header.component.ts, src/app/header/login-handler/login-handler.component.ts, src/app/icons/status-icons/status-icons.component.html, src/app/services/validation/validation.service.ts, src/environments/environment.ts
entire tool workflow testing and bug fixing
minor bugs fixed
no multiple api triggers
=> Bnt logic improvement

src/app/app.module.ts, src/app/body/body.component.html, src/app/body/body.component.ts, src/app/body/update-team/update-team.component.css, src/app/body/update-team/update-team.component.html, src/app/body/update-team/update-team.component.spec.ts, src/app/body/update-team/update-team.component.ts, src/app/body/view-organization-details/teams-card/teams-card.component.html, src/app/body/view-organization-details/teams-card/teams-card.component.ts, src/app/services/popup-handler/popup-handler.service.ts
Signed-off-by: sid-bagwe <siddhesh.ab@somaiya.edu>
Added update team
Seperated update team from create team.
Used older logic itself
ng serve
auto setup
Try updating a team
=> feat(dev/updateTeam): Added update team

src/app/body/profile/edit-profile/edit-profile.component.html
Changed the Edit Profile Page to the proposed design
Changed the page structure using Bootstrap
=> changed the edit profile page

src/app/body/tasks-evaluation/tasks-evaluation.component.ts
Load more button in TASK EVALUATION page
Previous sprint details along with backlog is now visible when load more button is clicked
Click on load more button in task evaluation page
=> Dev task evaluation

src/app/body/navbar/navbar.component.css, src/app/body/profile/profile.component.html
Removed duplicate profile header 
added css to the navbar components
including profile
ng serve -o
=> fix(profileHeader): added css to Profile header

src/app/body/profile/edit-profile/edit-profile.component.css, src/app/body/profile/edit-profile/edit-profile.component.html, src/app/body/profile/edit-profile/edit-profile.component.ts
Changed the design of Edit Profile Page
Changed the design of Edit Profile Page in profile component
=> fix/editprofileaccess: fixed the edit-profile

src/app/body/board/board.component.ts, src/app/body/body.component.html, src/app/services/applicationSettings/application-settings.service.ts, src/app/services/start/start-service.service.ts
team switch in board page
loading the data correctly upon switching the team in board page
Go to board page and try switching teams
=> fix(teamSwitch): data fetched for team switch

src/app/body/profile/profile.component.ts, src/app/services/user-service/user-service.service.ts
Made Other Users Profile  Viewable
Used the Users data fetched while clicking on the users' profile picture in app-suggestion bucket.
- Create Two Users
- Assign a task to the second user
- Click on the second user from the task details component
- Chck whether the Profile of the second user is visible
- Now navigate to my profile and check whether the first users profile is visible
=> fix(UserProfile):Fixed User Profile

src/app/body/task-details/upload-files/upload-files.component.html, src/app/services/fileUploadService/file-upload.service.ts
- Made Files to show up immediately after upload and disappear immediately after delete
- Improved Upload files UI
- Called the ReadFiles in upload service
- Upload a file and check whether the file shows up immediately.
- Delete a file and check whether it Disappears immediately.
=> fix(TaskUploadDocument):fixed Upload Document

src/app/body/task-details/edit-page/edit-page.component.css, src/app/body/task-details/edit-page/edit-page.component.html
swapped the assignee and creator name and font
made changes in html and css
ng serve -o
edit task
=> fix(editTaskUI): fixed the UI

src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/board/sprint-details/sprint-details.component.ts
Fix the sprint details
Implemented the loader functionality by using loader component and fetched the sprint details after the sprint status change.
By completing the current sprint
=> fix(sprint-details):fixed the UI and added loader

src/app/app.module.ts, src/app/body/board/board.component.html, src/app/body/board/sprint-burndown-chart/sprint-burndown-chart.component.css, src/app/body/board/sprint-burndown-chart/sprint-burndown-chart.component.html, src/app/body/board/sprint-burndown-chart/sprint-burndown-chart.component.spec.ts, src/app/body/board/sprint-burndown-chart/sprint-burndown-chart.component.ts, src/app/body/common-tools/chart/chart.component.html, src/app/body/common-tools/chart/chart.component.ts, src/app/body/my-dashboard/performance-chart/performance-chart.component.html, src/assets/errorCodes.xml
Signed-off-by: sid-bagwe <siddhesh.ab@somaiya.edu>
Created a sprint burndown chart
Created a sprint burndown chart
ng serve
=> feat(sprintBurnDownChart): Created a sprint burndown chart

functions/model/tasks/tark/createTask.js, functions/model/users/lib.js, src/app/header/notification-center/notification-center.component.ts
- Fixed Notification Counter
- Fixed Notification Creator
- Added console logs for checking the notification issue after deployment
- Refreshed the Active notifications value after clicking the notifications
- Changed the Uid of the notification receiver
- Click the notifications, see the notifications getting zero
- Create a task and check whether the notification is received by the assignee and not the creator
=> fix(Notifications):Fixed counter,notification Creator

src/app/body/common-tools/data-table/data-table.component.html, src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.html, src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.ts, src/app/body/create-new-task/create-new-task.component.html, src/app/body/kanban-board/kanban-board.component.html, src/app/body/task-details/edit-page/edit-page.component.html, src/app/body/task-details/task-details.component.html, src/app/body/tasks-evaluation/task-ecard/task-ecard.component.html
Fixed the suggestion-bucket
Removed the email tag in suggestion bucket
=> fix(suggestion-bucket):removed email

functions/model/tasks/tark/createTask.js, functions/model/users/lib.js, src/app/app.module.ts, src/app/body/board/board.component.html, src/app/body/board/sprint-burndown-chart/sprint-burndown-chart.component.css, src/app/body/board/sprint-burndown-chart/sprint-burndown-chart.component.html, src/app/body/board/sprint-burndown-chart/sprint-burndown-chart.component.spec.ts, src/app/body/board/sprint-burndown-chart/sprint-burndown-chart.component.ts, src/app/body/common-tools/chart/chart.component.html, src/app/body/common-tools/chart/chart.component.ts, src/app/body/common-tools/data-table/data-table.component.html, src/app/body/common-tools/profile-pictures/profile-pictures.component.css, src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.html, src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.ts, src/app/body/create-new-task/create-new-task.component.html, src/app/body/create-new-task/create-new-task.component.ts, src/app/body/kanban-board/kanban-board.component.css, src/app/body/kanban-board/kanban-board.component.html, src/app/body/kanban-board/kanban-board.component.ts, src/app/body/my-dashboard/performance-chart/performance-chart.component.html, src/app/body/quick-notes/addnew-note/addnew-note.component.html, src/app/body/quick-notes/addnew-note/addnew-note.component.ts, src/app/body/task-details/edit-page/edit-page.component.html, src/app/body/task-details/task-details.component.html, src/app/body/tasks-evaluation/task-ecard/task-ecard.component.html, src/app/body/view-organization-details/teams-card/teams-card.component.html, src/app/header/notification-center/notification-center.component.ts, src/app/services/applicationSettings/application-settings.service.ts, src/assets/errorCodes.xml, src/environments/environment.ts
Internal Release 4.9
1. fixed Teams Card
2. Automated quick notes Title.
3. Removed email from suggestion bucket.
4.  Created a sprint burndown chart 
5. Fixed Kanban board
6. added loader upon project change in create new task popup
7. fixed notifications and counter
8. Added GitHub workflow for automated deployment.
In Internal Release 4.9
=> Internal Release 4.9

src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.html
Fixed Suggestion bucket
Fixed suggestion bucket
Direct deployement
=> Fixed - Suggestion bucket

firestore.indexes.json, functions/model/teams/lib.js, functions/model/teams/tark/getTeamData.js, src/app/body/create-new-team/create-new-team.component.ts, src/app/body/my-dashboard/my-dashboard.component.html, src/app/body/my-dashboard/my-dashboard.component.ts, src/app/body/view-organization-details/view-organization-details.component.html, src/app/body/view-organization-details/view-organization-details.component.ts, src/app/header/header.component.html, src/app/services/applicationSettings/application-settings.service.ts, src/app/services/start/start-service.service.ts, src/environments/environment.ts
=> fix(workflow): fixed create new team workflow

src/app/body/task-details/upload-files/upload-files.component.html
the upload file button should upload files
replaced anchor tag with label tag
By selecting the upload files button and upload files
=> fix(uploadfiles):replaced anchor tag with label tag

src/app/body/create-new-task/create-new-task.component.ts
fixed pop up
changes in ts
ng serve -o
=> fix(popUp):fixed

src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts
Comment button is not blocked and its not updating immediately
Implemented a loader which stops multiple comments
By giving a test comment
=> fix(comment):fixed comment

src/app/body/create-new-task/create-new-task.component.css, src/app/body/create-new-task/create-new-task.component.html, src/app/body/create-new-task/create-new-task.component.ts
direct buttons pointing at active and backlog sprint
added the html and methods in ts related to the buttons
ng serve -o
=> feat(directButtons): added sprint direct buttons

src/app/body/github-link/github-link.component.html, src/app/body/github-link/github-link.component.ts, src/app/services/http-service.service.ts
Signed-off-by: Abhishek Mishra <am1426620@gmail.com>
fix github integration
fixed Github integration API trigger
on my Organisation page, click integrate GitHub for a team .
=> fix(github-integration-api-trigger): "fixed github integration api link"

functions/model/mailer/lib.js, functions/model/tasks/tark/addComment.js, functions/model/tasks/tark/addWatcher.js, functions/model/tasks/tark/createTask.js, functions/model/tasks/tark/deleteTask.js, functions/model/tasks/tark/editTask.js, functions/model/tasks/tark/logwork.js, functions/model/users/tark/addEducation.js, functions/model/users/tark/addExperience.js, functions/model/users/tark/addProject.js, functions/model/users/tark/addUserEmail.js, functions/model/users/tark/updateEducation.js, functions/model/users/tark/updateExperience.js, functions/model/users/tark/updateProfilePic.js, functions/model/users/tark/updateProject.js, functions/model/users/tark/updateSkills.js, functions/model/users/tark/updateUser.js
Implemented Mailer Mechanism
Implemented Mailer Mechanism
=> feat(mailer):Implemented Mailer mechanism

src/app/body/social-page/posts/comments/comments.component.html, src/app/body/social-page/posts/comments/comments.component.ts
commenters correct name will get displayed
changes in comments component
ng serve -o
=> fix(comments): commenters correct name will get displayed

src/app/services/start/start-service.service.ts
Profile page is loading properly with the data 
Made changes in start-service
ng serve -o
=> fix(profilePage): fixed the bug in profilePage

src/app/body/social-page/social-page.component.html, src/app/body/social-page/social-page.component.ts
Made the latest 3 posts of the user visible in the recent posts section
filtered out the users latest posts
by creating a post
=> Fix/Recent files : Added recent Posts

src/app/body/task-details/edit-page/edit-page.component.css, src/app/body/task-details/edit-page/edit-page.component.html, src/app/body/task-details/edit-page/edit-page.component.ts
added sprint direct button
added sprint direct button
=> fix/sprintpage: added sprint direct button

functions/model/teams/teams.js
fixed ESLint errors.
fixed ESLint errors.
In ```functions/model/teams/teams.js```
=> fixed ESLint errors.

functions/index.js, functions/model/milestone/lib.js, functions/model/milestone/milestone.js, functions/model/milestone/tark/addMilestone.js, functions/model/milestone/tark/getAllMilestones.js, functions/model/milestone/tark/getMilestone.js, functions/model/tasks/lib.js, functions/model/tasks/tark/createTask.js, functions/model/tasks/tark/editTask.js, functions/model/tasks/tark/getTasks.js, src/app/Interface/MilestoneInterface.ts, src/app/Interface/TasksInterface.ts, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/body/create-new-task/create-new-task.component.html, src/app/body/create-new-task/create-new-task.component.ts, src/app/body/milestone-details/milestone-details.component.css, src/app/body/milestone-details/milestone-details.component.html, src/app/body/milestone-details/milestone-details.component.spec.ts, src/app/body/milestone-details/milestone-details.component.ts, src/app/body/milestone/milestone.component.css, src/app/body/milestone/milestone.component.html, src/app/body/milestone/milestone.component.spec.ts, src/app/body/milestone/milestone.component.ts, src/app/body/task-details/edit-page/edit-page.component.html, src/app/body/task-details/edit-page/edit-page.component.ts, src/app/header/header.component.html, src/app/header/header.component.ts
Created MilestoneComponent
Users can create a milestone or plan and add tasks to it
Go to milestones and create a milestone
After creating a milestone create a task with the milestone id
Click on the milestone card to see the milestone Details
=> feat(Milestone):Created Milestonecomponent

src/app/body/profile/edit-profile/edit-profile.component.css, src/app/body/profile/edit-profile/edit-profile.component.html, src/app/body/profile/edit-profile/edit-profile.component.ts
fix check username in profile page
Changes in edit-profile component
in profile page click on edit profile then change username and click on check availability button its shows loader first and then show username available message
=> Fix(check username):fix check username

src/app/body/social-page/posts/posts.component.css, src/app/body/social-page/posts/posts.component.html, src/app/body/social-page/posts/posts.component.ts
…n onclick
<-- Added color to star button onclick and fixed the comments(closes when clicked once) -->
<-- added ngClass to add color to star button onclick -->
<-- 1. ng serve & firebase emulators:start.
2.  go to social page.
3. click on create post.
4. click on star icon(you can see the added color).
5. double click on comments (comment box opens and closes). -->
=> fix(posts-component)fixed the comments of posts and added color to star icon onclick

functions/model/milestone/lib.js, functions/model/milestone/tark/addMilestone.js, src/app/Interface/MilestoneInterface.ts, src/app/app-routing.module.ts, src/app/body/create-new-task/create-new-task.component.html, src/app/body/create-new-task/create-new-task.component.ts, src/app/body/milestone-details/milestone-details.component.css, src/app/body/milestone-details/milestone-details.component.html, src/app/body/milestone-details/milestone-details.component.ts, src/app/body/milestone/milestone.component.css, src/app/body/milestone/milestone.component.html, src/app/body/milestone/milestone.component.ts, src/app/body/task-details/edit-page/edit-page.component.html, src/app/body/task-details/edit-page/edit-page.component.ts, src/app/header/header.component.ts, src/app/services/popup-handler/popup-handler.service.ts
Improved Milestone component
Improved the UI of Milestones component.
Added Features to the Milestone Details Component
- Users can add existing tasks from milestone details component
- Users can Create a new task with current milestone Id
Added a Task Tracker
- Go to Milestone component
- Add a Milestone
- Click on the milestone Card
- Add some Tasks to the milstone
=> feat(Milestone):Improved Milestone Component

functions/model/users/tark/getUserByUsername.js, functions/model/users/users.js, src/app/body/profile/profile.component.html, src/app/body/profile/profile.component.ts
- Made the Username route work for profile page
- Removed edit option for other users from education, project and experience.
- Brought Data from Database if the data is not stored in the service
- Used ng-if to hide the edit button
Copy the username of other users and put in the url and check if the data displayed is correct.
Check whether the edit option is visible for other users, it should not be visible.
=> fix(ProfilePage): Made username route work

src/app/body/body.component.css, src/app/footer/footer.component.css, src/app/footer/footer.component.html
fixed the home Page Footer
fixed the footer
Check the Home Page Footer
=> fix(footer):fixed the homePageFooter

functions/model/mailer/lib.js, functions/model/mailer/tark/generateTemplate.js, functions/model/mailer/templates/addEducation.html, functions/model/mailer/templates/addExperience.html, functions/model/mailer/templates/addProjectProfile.html, functions/model/mailer/templates/comment.html, functions/model/mailer/templates/createTask.html, functions/model/mailer/templates/deleteTask.html, functions/model/mailer/templates/editProfile.html, functions/model/mailer/templates/editTask.html, functions/model/mailer/templates/logTask.html, functions/model/mailer/templates/updateEducation.html, functions/model/mailer/templates/updateExperience.html, functions/model/mailer/templates/updatePic.html, functions/model/mailer/templates/updateProject.html, functions/model/mailer/templates/updateSkill.html, functions/model/mailer/templates/verificationMail.html, functions/model/mailer/templates/watcher.html
Improved mailer Logic and content
Improved logic for sending mails to the watchers and assignees.
Improved the HTML content of mails.
Do all the below operations and test the mail.
addComment, addWatcher, createTask, deleteTask, editTask, logWork, addEducation, addExperience, addProject, updateEducation, updateExperience, updateProfilePic, updateProject, updateSkills, updateUser, addUserEmail.
=> feat(Mailer):Improved Mailer Logic and content

src/app/body/quick-notes/addnew-note/addnew-note.component.ts, src/app/body/quick-notes/quick-notes.component.html, src/app/body/quick-notes/quick-notes.component.ts
fix the quick notes 
Changes done in quick-notes components
1. click on quick note then  add note and click on save button then it shows loader and after that it show note 
2. click on delete note icon then it shows loader and then note delete
=> fix(quick notes):fix the quick notes

src/app/body/release-notes/release-notes-body/release-notes-body.component.html, src/app/body/release-notes/release-notes-body/release-notes-body.component.ts
Signed-off-by: Abhishek Mishra <am1426620@gmail.com>
fixing release notes in the footer
fixed release notes according to new format of release data
in footer, click build
=> fix(build notes): fixing release notes

src/app/body/profile/edit-profile/edit-profile.component.html, src/app/body/profile/edit-profile/edit-profile.component.ts
fix(username availability):fix check username availability
Changes done in edit-profile-component
go to profile page click on edit profile and change username .
=> fix (username availability):check username availability

src/app/body/create-new-organization/create-new-organization.component.html, src/app/body/task-details/task-details.component.html
Include the labels on the top of input fields
Changes done in create-new-organization component
click on profile icon then click on create new organization
=> fix(create new Organization labels):Include the labels on the top of input fields

src/app/body/create-new-team/create-new-team.component.css, src/app/body/create-new-team/create-new-team.component.html
<-- Changed the UI of create-new-team-->
<-- Did some changes in create-new-team component. -->
<-- please tell us how to test functionality/bug 
steps: 1. ng serve and firebase emulators:start
2.  go to My Organization
3.  go to create-new-team
4.  there you can see the changes in UI.-->
=> Fix create new team

src/app/body/social-page/whats-new/whats-new.component.html, src/app/body/social-page/whats-new/whats-new.component.ts
Features will get displayed under worktez updates in social page
made changes in what'sNewComponent
ng serve -o
firebase emulators: start
=> fix(worktezFeatures): Displayed Features

src/app/body/board/sprint-details/sprint-details.component.ts
we can switch from backlog and deleted back to active sprint 
made a change in sprintDetailsPage ts file
ng serve -o
=> fix(sprintSwitchBug): fixed sprint switch bug

.vscode/settings.json, src/app/body/board/board.component.ts, src/app/body/body.component.css, src/app/body/body.component.html, src/app/body/body.component.ts, src/app/body/common-tools/theme/theme.component.html, src/app/body/kanban-board/kanban-board.component.ts, src/app/body/milestone-details/add-task/add-task.component.ts, src/app/body/milestone-details/milestone-details.component.ts, src/app/body/milestone/add-milestone/add-milestone.component.ts, src/app/body/milestone/milestone.component.ts, src/app/body/tasks-evaluation/tasks-evaluation.component.ts, src/app/services/validation/validation.service.ts, src/assets/errorCodes.xml
Fixed bugs and Added theme changer button all over the application in emulator mode.
-  Fixed Error name for Reporter validation
-  Fixed Error code for Assignee and Reporter Validation
-  Added Theme changer all over the application in emulator mode
-  Added Date validation for start and end date
-  Updated TeamId in cookeies, Whenever it is updated in db
-  Added Error code for milestone
- check the validation error code and message for assignee and reporter  in create new task.
- Try changing theme in the application in emulator mode.
- Try adding text in date field 
- Check whether the cookies are updated when we change the team
- Check for error code in milestone related components
=> fix(bugs): Fixed bugs, added theme changer button

src/app/body/quick-notes/addnew-note/addnew-note.component.css, src/app/body/quick-notes/addnew-note/addnew-note.component.html, src/app/body/quick-notes/addnew-note/addnew-note.component.ts, src/app/body/quick-notes/edit-note/edit-note.component.css, src/app/body/quick-notes/edit-note/edit-note.component.html, src/app/body/quick-notes/edit-note/edit-note.component.ts, src/app/body/quick-notes/quick-notes.component.css
to fix quicknotes keeps loading on create task
fixed quicknotes loading in create task and minor UI changes
try creating a task from quicknotes keeping the notes empty
=> fix(quicknotes): "fixed quicknotes loading on create task"

src/app/body/board/performance-column-chart/performance-column-chart.component.html, src/app/body/board/performance-column-chart/select-dropdown/select-dropdown.component.css, src/app/body/board/performance-column-chart/select-dropdown/select-dropdown.component.html, src/app/body/board/performance-column-chart/select-dropdown/select-dropdown.component.ts, src/app/body/board/sprint-details/sprint-details.component.css, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/filter-task/filter-task.component.css, src/app/body/filter-task/filter-task.component.html, src/app/body/kanban-board/kanban-board.component.css, src/app/body/kanban-board/kanban-board.component.html, src/app/body/my-dashboard/performance-chart/range-card/range-card.component.css, src/app/body/my-dashboard/performance-chart/range-card/range-card.component.html, src/app/body/tasks-evaluation/tasks-evaluation.component.css, src/app/body/tasks-evaluation/tasks-evaluation.component.html, src/app/body/tasks/tasks.component.ts
to fix popups in boards page, and make them identical
fixed the popups in boards , mydashboard , task evaluation page and kanban board
step1: check all the popups in the above mentioned boards by clicking them
=> fix(popups): 'fixing popups in boards page'

src/app/body/create-new-task/create-new-task.component.css, src/app/body/create-new-task/create-new-task.component.html, src/app/body/profile/edit-profile/edit-profile.component.html, src/app/body/social-page/create-post/create-post.component.css, src/app/body/social-page/create-post/create-post.component.html, src/app/body/social-page/create-post/create-post.component.ts
fix create-new-task and new-post popup
changes done in  create-new-task and create-post component 
1. go to social page and click on create post 
2. click on create option on navbar
=> fix(popup):Fix New post popup, New task popup

src/app/body/board/performance-column-chart/select-dropdown/select-dropdown.component.css, src/app/body/board/sprint-details/sprint-details.component.css, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/kanban-board/kanban-board.component.css, src/app/body/my-dashboard/performance-chart/range-card/range-card.component.css, src/app/body/my-dashboard/performance-chart/range-card/range-card.component.html
to fix popups in board pages
fixed the popups in board page, my dashboard, task evaluation page, kanban board and made them look similar to each other
check for all the popups in all the board pages
=> fix(popups): 'fixed board pages popups'

functions/model/mailer/tark/generateTemplate.js, functions/model/mailer/templates/comment.html, functions/model/mailer/templates/createTask.html, functions/model/mailer/templates/deleteTask.html, functions/model/mailer/templates/editTask.html, functions/model/mailer/templates/logTask.html, functions/model/mailer/templates/watcher.html
Made the Links in the mails functioning.
Made changes in the Templates to make the links work.
Do all task related activities and check whether the link in the mail is redirecting to Correctly.
=> fix(mailer): Fixed Links in Mails

src/app/body/profile/edit-education/edit-education.component.css, src/app/body/profile/edit-education/edit-education.component.html, src/app/body/profile/edit-profile/edit-profile.component.css, src/app/body/profile/edit-profile/edit-profile.component.html, src/app/body/profile/edit-projects/edit-projects.component.css, src/app/body/profile/edit-projects/edit-projects.component.html, src/app/body/profile/edit-skills/edit-skills.component.css, src/app/body/profile/edit-skills/edit-skills.component.html, src/app/body/profile/edit-workexperience/edit-workexperience.component.css, src/app/body/profile/edit-workexperience/edit-workexperience.component.html
fix profile page all popup 
changes done in profile component 
click on profile and chick all popups
=> Fix(Popups):Fix profile page all popups

src/app/body/kanban-board/kanban-board.component.css, src/app/body/kanban-board/kanban-board.component.html, src/app/body/kanban-board/kanban-board.component.ts
made the kanban Board columns dynamic and implemented a dropdown menu and Icons
sliced the array to make the kanban board columns dynamic
=> fix/kanbanBoardcolumn 

src/app/header/header.component.html
Fix Organization dropdown
Change done in header component 
Click on Organization dropdown
=> Fix(dropdown):Fix Organization dropdown

src/app/body/task-details/log-work/log-work.component.css, src/app/body/task-details/log-work/log-work.component.html, src/app/body/task-details/log-work/log-work.component.ts, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts
fix comment section and log-work functionality
Changes done in task-details component 
go to task detail page and comment and log-work and mark task completed without marking log-work 100% and submit it automatically mark completed and on reopen it mark 0%.
=> fix(task details):task details bug

src/app/body/social-page/whats-new/whats-new.component.html, src/app/body/social-page/whats-new/whats-new.component.ts
feature display in worktez updates section 
made changes in whats New component
ng serve -o
=> fix(WhatsNewComponent): worktez updates section

.github/workflows/firebase-hosting-merge.yml
Fixed release work flow
changed npm install command to force
firebase-hosting-merge.yml
=> fix: Release workflow

src/app/body/task-details/git/git.component.css, src/app/body/task-details/git/git.component.html, src/app/body/task-details/git/git.component.ts, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts, src/app/services/popup-handler/popup-handler.service.ts
Added Edit functionality in PR
Added Edit functionality in PR Integeration
By creating and adding another PR
=> fix:Pr Added Edit functionality in PR Integeration

src/app/body/board/sprint-details/sprint-details.component.css, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/create-new-sprint/create-new-sprint.component.css, src/app/body/create-new-sprint/create-new-sprint.component.html
Fixed the UI of sprint popups.
Changes done in sprint-details and create new sprint components.
Steps to check :
1. open emulator
2. go to board from boards
3. click on create new sprint.
4. you can see the new UI of create new sprint popup  and test it further.
=> fix(sprint-details/create-new-sprint):fixed Ui of sprint popups

src/app/body/common-tools/warning/warning.component.css, src/app/body/common-tools/warning/warning.component.html, src/app/body/create-new-task/create-new-task.component.html, src/app/body/create-new-team/add-member/add-member.component.css, src/app/body/create-new-team/add-member/add-member.component.html, src/app/body/create-new-team/create-new-team.component.css, src/app/body/create-new-team/create-new-team.component.html, src/app/body/github-link/github-link.component.css, src/app/body/github-link/github-link.component.html, src/app/body/milestone/add-milestone/add-milestone.component.css, src/app/body/profile/edit-profile/edit-profile.component.html, src/app/body/profile/edit-projects/edit-projects.component.html, src/app/body/profile/edit-workexperience/edit-workexperience.component.css, src/app/body/profile/edit-workexperience/edit-workexperience.component.html, src/app/body/task-details/edit-page/edit-page.component.css, src/app/body/task-details/edit-page/edit-page.component.html, src/app/body/task-details/link/link.component.css, src/app/body/task-details/link/link.component.html, src/app/body/update-team/update-team.component.css, src/app/body/update-team/update-team.component.html
Fixed all the popus UI
Changes done in html and css of various components shown below
step1: open emulator
step2: you can see all popups are fixed and made similar.
=> Fix(UI):fixed all popus

src/app/body/milestone-details/milestone-details.component.css, src/app/body/milestone/milestone.component.css
Changed the buttons UI
Changes done in milestone and milestone-details component
step1: open emulator
step2: go to milestone you can see the changes
step3: to see changes in milestone details click on any milestone the changes will be visible.
=> Fix (milestone/milestone-details):fixed buttons UI

src/app/body/common-tools/data-table/data-table.component.html, src/app/body/common-tools/data-table/data-table.component.ts
Added Default Sort for Data table
When the User selects a Sort  in Data table, it Stays locally until they change it.
Sort a column, Go to some other page and Come back to the same page and see if the Sort you selected stays.
=> fix(Sort): Fixed Default Sort

functions/model/linker/lib.js, functions/model/linker/linker.js, functions/model/linker/tark/removeLink.js, src/app/Interface/TasksInterface.ts, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts
provided an option to delete links
provided an option to delete the links and unlink the PR in task details.
by adding another PR or a link and deleting them
=> fix(DeleteLinks):provided an option to delete links

src/app/body/task-details/task-details.component.html
To fixed the comment section in the task details page. 
The lines of the comments section paragraph given in the comment section are now appearing as they are typed in the comment box.
1. Go to task details page .
2. Go to comment section. 
3. Drop any comment line wise line.
=> fixed (Comment Section ) bug

src/app/body/team-details/edit-label-prop/edit-label-prop.component.html, src/app/body/team-details/edit-label-prop/edit-label-prop.component.ts
made the ui of edit Label proper and added option to select color and icon 
made changes in edit label component
ng serve -o
=> fix(editLabel): fixed edit Label popup

src/app/body/filter-page/edit-filter/edit-filter.component.css, src/app/body/filter-page/edit-filter/edit-filter.component.html, src/app/body/filter-page/edit-filter/edit-filter.component.ts, src/app/body/filter-page/filter-page.component.css
Fixed the ui of edit and delete in filter page
made changes in filter component
ng serve -o
=> fix(filterPageUI): fixed edit and delete ui

src/app/body/filter-task/filter-task.component.css, src/app/body/filter-task/filter-task.component.html, src/app/body/filter-task/filter-task.component.ts
fixed the filter task in tasks page
made changes in filterTasks component
ng serve -o
=> fix(filterTask): made the ui fixes in tasks page filter

functions/model/filters/lib.js, functions/model/mailer/lib.js
fixed eslint errors in the release
Fixed errors
internal release 6.1
=> fixed eslint errors in the release

src/app/body/team-details/team-details.component.css, src/app/body/team-details/team-details.component.html
Added a warning delete Team PopUp
Made changes in team details component
ng serve -o
=> fix(deleteTeam): Added a warning delete Team  popup

src/app/app-routing.module.ts, src/app/body/login/login.component.ts, src/app/body/social-page/social-page.component.ts, src/app/header/header.component.ts, src/app/services/auth.service.ts, src/app/services/start/start-service.service.ts
Tech Tag page is now reloading properly
made changes in social page component 
ng serve -o
=> fix(techTagReload): fixed tech tag reload

functions/model/sprints/tark/updateSprintStatus.js, src/app/body/board/sprint-details/sprint-details.component.ts
On creating new sprint progress bar was not working.
Now On completing the sprint on the same day its working
1. Go to boards page.
2. Create New sprint and mark it as completed.
=> Fixed progress bar in Boards page

src/app/body/task-details/task-details.component.html
created a plus sign for adding links in links section of task details page
Plus sign created
Go to task details page and add link there.
=> fix{iconAdded} : added plus icon in task details page {linksSection}

src/app/body/home/home.component.css, src/app/body/home/home.component.html, src/app/body/home/home.component.ts, src/app/body/home/testimonial-card/testimonial-card.component.css, src/app/body/home/testimonial-card/testimonial-card.component.html, src/app/body/home/testimonial-card/testimonial-card.component.ts, src/index.html
Signed-off-by: Abhishek Mishra <am1426620@gmail.com>
changing the font in the homepage and updating the testimonials
updated the font to 'Plus Jakarta Sans' and updated the testimonials
visit worktez homepage to observe the changes in fonts and testimonials
=> fix(homepage) : Updating font and testimonials in homepage

src/app/body/common-tools/data-table/data-table.component.css, src/app/body/filter-task/filter-task.component.css, src/app/body/milestone/milestone.component.css, src/app/body/my-dashboard/my-tasks/my-tasks.component.css, src/app/body/task-details/link/link.component.css, src/app/body/task-details/link/link.component.html, src/app/body/view-organization-details/view-organization-details.component.css
darkmode issues are fixed
made changes in the respective css files
ngserve 
firbaseemulator: start
=> fix (darkmode): fixed dark mode issues

functions/model/socialPage/lib.js, functions/model/socialPage/socialPage.js, functions/model/socialPage/tark/deletePost.js, functions/model/socialPage/tark/getPosts.js, src/app/Interface/SocialInterface.ts, src/app/body/social-page/posts/posts.component.css, src/app/body/social-page/posts/posts.component.html, src/app/body/social-page/posts/posts.component.ts
Added delete function to Post.
Changes in Post component,and made Api  in tark file of social page.
Steps to check:-
1. open emulator.
2. go to Techtag.
3. create post and use the dropdown to delete post.
4. Also you can check the status of post chaning from "OK" to "DELETED" in firestore emulator.
=> feat(posts):Added delete function to Post

src/app/body/task-details/task-details.component.html
improved css of task details page
fixed task title position
ng serve
=> fixed (taskTitle)

src/app/body/filter-task/filter-task.component.css, src/app/body/filter-task/filter-task.component.html, src/app/body/filter-task/filter-task.component.ts
added custom filter option on tasks page
made changes in filter-tasks component
ng serve -o
=> feat(customerFilter): added custom filter option in tasks page

src/app/body/quick-notes/quick-notes.component.html, src/app/body/quick-notes/quick-notes.component.ts
Fixed delete functionality and loader in Quick Note
Delete button is working properly.
1. Go ton Worktez
2. Go to QuickNotes, make notes and check it.
=> Fixed changes in Note

functions/model/performanceChart/tark/getPerformanceChartData.js
fixed the sprint filter in team performance chart in mydashboard and board page
fixed the sprint filter in team performance chart
fixed the range in filters
Check the filter in performance chart
=> fixed(sprintFiltersCharts)

src/app/body/profile/profile.component.ts, src/app/body/social-page/posts/posts.component.html, src/app/body/social-page/posts/posts.component.ts
profile redirection is working after visiting someone else profile.
changes in profile component and 
steps to check :-
1. open emulator
2. create  posts of two different users .
3. visit users profile from post .
4. click on profile on user card.
5. you will be redirected to your profile.
=> fix(profile/posts):fixed profile redirection bug and added reveresed changes of suggestion bucket

src/app/user-verification/user-verification.component.ts
on clicking on verify we were getting 404 error ..resolved it
made a change in user verification component
ng serve -o
=> fix(verifyButton): fixed verify button

src/app/body/social-page/posts/posts.component.css, src/app/body/social-page/posts/posts.component.html
fixed the UI for smaller screens
Improved the responsiveness by boostrap
=> fix(techtagUi):fixed the UI for smaller screens

functions/model/milestone/lib.js, functions/model/milestone/milestone.js, functions/model/milestone/tark/addTask.js, src/app/body/create-new-task/create-new-task.component.ts, src/app/body/milestone-details/add-task/add-task.component.ts, src/app/body/milestone-details/milestone-details.component.html, src/app/body/milestone-details/milestone-details.component.ts, src/app/body/milestone/milestone-card/milestone-card.component.css, src/app/body/milestone/milestone.component.css, src/app/services/milestone-service.service.spec.ts, src/app/services/milestone-service.service.ts
Fixed Milestone Component
- Fixed Milestone Add Task
- Fixed Task Data refresh on Create new Task
Try Adding tasks to milestone, check whether it is getting added.
Create a new task and check whether it is visible in task tracker
=> fix(Milestone):Fixed Milestone Add Task

functions/model/users/tark/checkIfUserAlreadyAMember.js, functions/model/users/users.js, src/app/user-verification/user-verification.component.html, src/app/user-verification/user-verification.component.ts
On clicking on verify any number of times member will get added only once to the team
Made changes in user verification component
ng serve -o
=> fix(emailVerification): fixed email verification

src/app/body/common-tools/update-image/update-image.component.html, src/app/body/common-tools/update-image/update-image.component.ts, src/app/body/profile/edit-profile-pic/edit-profile-pic.component.ts, src/app/body/profile/profile.component.ts
to fix edit profile
edit Profile fixed
1. Go to edit profile.
2. Set the profile.
=> fixed edit profile

functions/model/milestone/lib.js, functions/model/milestone/tark/addTask.js
fixed lint issues
fixed lint issues
in internal release
=> fixed eslint issues

functions/model/sprints/tark/updateSprint.js, functions/model/tasks/tark/editTask.js
Fix Sprint Data Changes on Edit Task
Removed the condintions with Status Labels.
Instead Used the Current Sprint Value for comparison
Try Editing Tasks from one sprint to another
Try Editing the Story points
=> fix(EditTask):Fixed Sprint Data Changes

functions/model/scheduledFunctions/lib.js, functions/model/tasks/tark/editTask.js, functions/model/teams/tark/addMember.js, functions/model/teams/tark/createTeam.js, functions/model/users/tark/checkIfUserAlreadyAMember.js, functions/model/users/tark/verifyUser.js
fixed release errors
fixed release errors
In Internal Release 6.4
=> fixed release errors

functions/model/meet/lib.js, functions/model/meet/meet.js, functions/model/meet/tark/getMeetDetails.js, src/app/Interface/MeetInterface.ts, src/app/app.module.ts, src/app/header/header.component.css, src/app/header/header.component.html, src/app/header/show-meet-details/show-meet-details.component.css, src/app/header/show-meet-details/show-meet-details.component.html, src/app/header/show-meet-details/show-meet-details.component.spec.ts, src/app/header/show-meet-details/show-meet-details.component.ts
Created UI to show meet details.
added show-meet-details component and did changes in meet component
Steps to check:-
2. click on meet icon.
3. schedule meet
4. You can see the meet details below that.
=> ui(Show-meet-details):Added Ui to show meet details

src/app/header/show-meet-details/show-meet-details.component.css, src/app/header/show-meet-details/show-meet-details.component.html
Join button is used to join any scheduled meet.
changes in Show-meet-details component
steps to check:-
1.open emulator.
2.schedule a meet from meets
3.reload the page.
4.you can see the scheduled meet.
5.click on join.
6.you will be redirected to the meet.worktez.com/"yourRoomId".
.
=> fix(Show-meet-details):fixed join button in scheduled meet

angular.json, src/app/body/task-details/task-details.component.ts
the assignee's email and the picture are not updated immediately after we edit the task. Fix it.
made changes in tasks-details.component.ts
Go to edit task and change the assignee to see the results
=> Edit tasks fixed

src/app/body/profile/edit-education/edit-education.component.html, src/app/body/profile/edit-profile/edit-profile.component.html, src/app/body/profile/edit-profile/edit-profile.component.ts, src/app/body/profile/edit-projects/edit-projects.component.html, src/app/body/profile/edit-skills/edit-skills.component.html, src/app/body/profile/edit-skills/edit-skills.component.ts, src/app/body/profile/edit-workexperience/edit-workexperience.component.html
loader in profile page
fixed loader in profile page
Profile page --> edit skills, education, project, work experience
=> fixed loader in profile page

functions/model/sprints/tark/updateSprintStatus.js
fixed lint issues
fixed lint issues
ng serve -o
=> fixed lint issues

src/app/body/create-new-task/create-new-task.component.ts, src/app/body/task-details/task-details.component.html
when we create a task, the task type is not coming
made changes in createNewTask component
create a task
select the task type
=> changes done

src/app/body/profile/edit-education/edit-education.component.css, src/app/body/profile/edit-education/edit-education.component.html, src/app/body/profile/edit-profile/edit-profile.component.html, src/app/body/profile/edit-projects/edit-projects.component.html, src/app/body/profile/edit-skills/edit-skills.component.html, src/app/body/profile/edit-skills/edit-skills.component.ts, src/app/body/profile/edit-workexperience/edit-workexperience.component.html, src/app/body/profile/eductions/eductions.component.css, src/app/body/profile/eductions/eductions.component.html, src/app/body/profile/profile.component.css, src/app/body/profile/profile.component.html, src/app/body/profile/profile.component.ts, src/app/body/profile/projects/projects.component.css, src/app/body/profile/projects/projects.component.html, src/app/body/profile/skills/skills.component.html, src/app/body/profile/work-exp/work-exp.component.css, src/app/body/profile/work-exp/work-exp.component.html, src/app/body/view-organization-details/view-organization-details.component.html
Popup UI and reloading issue of skills.
fixed the UI and reloading issue of skills
Profile Page --> Edit your profile
=> fix: fixed the UI and reloading issue of skills

src/app/app.component.css, src/app/body/filter-page/create-filter/create-filter.component.html, src/app/body/filter-page/create-filter/create-filter.component.ts, src/app/body/filter-page/edit-filter/edit-filter.component.html, src/app/body/filter-page/filter-page.component.css, src/app/body/filter-page/filter-page.component.html, src/app/body/filter-page/filter-page.component.ts, src/app/body/filter-task/filter-task.component.ts, src/app/body/social-page/posts/posts.component.css, src/app/body/social-page/posts/posts.component.html, src/app/services/validation/validation.service.ts
Filter Page Fixing
All the components of filter Page are fixed
Go to the filter page and test the functionalities.
=> Fix filter

functions/model/organization/tark/changeMemberRole.js, functions/model/organization/tark/createMember.js, functions/model/organization/tark/getAllOrgMembers.js, functions/model/organization/tark/getMember.js, functions/model/users/tark/verifyUser.js, src/app/Interface/UserInterface.ts, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/quick-notes/edit-note/edit-note.component.html, src/app/body/quick-notes/edit-note/edit-note.component.ts, src/app/body/quick-notes/quick-notes.component.ts, src/app/body/view-organization-details/members-access/member-card/member-card.component.css, src/app/body/view-organization-details/members-access/member-card/member-card.component.html, src/app/body/view-organization-details/members-access/member-card/member-card.component.spec.ts, src/app/body/view-organization-details/members-access/member-card/member-card.component.ts, src/app/body/view-organization-details/members-access/members-access.component.css, src/app/body/view-organization-details/members-access/members-access.component.html, src/app/body/view-organization-details/members-access/members-access.component.spec.ts, src/app/body/view-organization-details/members-access/members-access.component.ts, src/app/body/view-organization-details/teams-card/teams-card.component.html, src/app/body/view-organization-details/teams-card/teams-card.component.ts, src/app/body/view-organization-details/view-organization-details.component.html, src/app/header/header.component.ts, src/app/services/RBA/rba.service.ts
fix some issues in devRba 
removed unnecessary code and fixed some errors
- [] low
check whether every functionality is working after the release
=> fix(Rba): fixed rba errors

src/app/body/filter-task/filter-task.component.css, src/app/body/view-organization-details/view-organization-details.component.html, src/app/body/view-organization-details/view-organization-details.component.ts, src/app/header/header.component.html, src/app/header/header.component.ts
Move the filters page to my organization page.
Changes done in my organization component
- [*] medium
go to my organization page and click on filter button
=> Move Filter Page

functions/model/tasksEvaluation/tark/readTasksEvalulationData.js, src/app/body/board/sprint-details/sprint-details.component.css, src/app/body/board/sprint-details/sprint-details.component.html, src/app/body/tasks-evaluation/tasks-evaluation.component.html, src/app/body/tasks-evaluation/tasks-evaluation.component.ts
Added Upcoming Sprint Bucket in Task Evaluation
Added Upcoming Sprint Bucket in Task Evaluation.
Changed the Sprint Filter UI. 
Try Dragging and Dropping tasks from Upcoming Spring Bucket in Task Evaluation Page
=> fix(taskEvaluation):Added Upcoming sprint

functions/model/socialPage/lib.js, functions/model/socialPage/socialPage.js, functions/model/socialPage/tark/addPost.js, functions/model/socialPage/tark/deleteComment.js, functions/model/socialPage/tark/getReactions.js, functions/model/socialPage/tark/removeReaction.js, functions/model/users/tark/incrementUserCounters.js, src/app/Interface/SocialInterface.ts, src/app/app-routing.module.ts, src/app/app.component.html, src/app/body/social-page/create-post/create-post.component.html, src/app/body/social-page/create-post/create-post.component.ts, src/app/body/social-page/posts/comments/comments.component.css, src/app/body/social-page/posts/comments/comments.component.html, src/app/body/social-page/posts/comments/comments.component.ts, src/app/body/social-page/posts/posts.component.css, src/app/body/social-page/posts/posts.component.html, src/app/body/social-page/posts/posts.component.ts, src/app/body/social-page/social-page.component.css, src/app/body/social-page/social-page.component.html, src/app/body/social-page/social-page.component.ts
improving the functionalities in tech tag
added no of stars in posts, Unstar post functionality, delete comment functionality, fixed no. of stars for the user, fixed image dimensions, arranged posts from latest to oldest
check each and every functionality in techtag
=> fix(Techtag): Techtag functionalities improvement

src/app/app.module.ts, src/app/body/common-tools/profile-pictures/profile-pictures.component.html, src/app/body/common-tools/speed-images/speed-images.component.html, src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.html, src/app/body/task-details/add-watchers/add-watchers.component.css, src/app/body/task-details/add-watchers/add-watchers.component.html, src/app/body/task-details/add-watchers/add-watchers.component.spec.ts, src/app/body/task-details/add-watchers/add-watchers.component.ts, src/app/body/task-details/edit-page/edit-page.component.ts, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts, src/app/services/validation/validation.service.ts
Add Watcher mechanism
Implemented a pop-up to add multiple watchers 
1. Go to Board --> Tasks --> task details.
2. Click on watchers and add a watcher.
=> feat: Added addWatcher mechanism

functions/index.js, functions/model/notifications/lib.js, functions/model/notifications/tark/emptyNotificationCount.js, functions/model/tasks/tark/addComment.js, functions/model/tasks/tark/addWatcher.js, functions/model/tasks/tark/createTask.js, functions/model/tasks/tark/deleteTask.js, src/app/Interface/NotificationInterface.ts, src/app/app-routing.module.ts, src/app/app.module.ts, src/app/header/notification-center/all-notification/all-notification-card/all-notification-card.component.css, src/app/header/notification-center/all-notification/all-notification-card/all-notification-card.component.html, src/app/header/notification-center/all-notification/all-notification-card/all-notification-card.component.spec.ts, src/app/header/notification-center/all-notification/all-notification-card/all-notification-card.component.ts, src/app/header/notification-center/all-notification/all-notification.component.css, src/app/header/notification-center/all-notification/all-notification.component.html, src/app/header/notification-center/all-notification/all-notification.component.spec.ts, src/app/header/notification-center/all-notification/all-notification.component.ts, src/app/header/notification-center/notification-center.component.css, src/app/header/notification-center/notification-center.component.html, src/app/header/notification-center/notification-center.component.ts, src/app/services/applicationSettings/application-settings.service.ts, src/app/services/start/start-service.service.ts
on click show older Notification it shows older Notification
Change done in notification-center component
- [*] medium
click on Notification icon and click on show older Notification
=> Fix Notifications

src/app/body/tasks-evaluation/task-ecard/task-ecard.component.css, src/app/body/tasks-evaluation/task-ecard/task-ecard.component.html
fixed task evaluation dropdown
made changes in task evaluation component
ng serve -o
=> fix(Assignee): fixed assignee dropdown task evaluation

firestore.indexes.json, functions/model/librarian/lib.js, functions/model/librarian/librarian.js, functions/model/librarian/tark/getFilesinOrganization.js, src/app/app.component.html, src/app/body/common-tools/update-image/update-image.component.ts, src/app/body/profile/profile.component.html, src/app/body/profile/profile.component.ts, src/app/body/social-page/posts/posts.component.css, src/app/body/social-page/posts/posts.component.html, src/app/body/view-organization-details/edit-dp/edit-dp.component.css, src/app/body/view-organization-details/edit-dp/edit-dp.component.html, src/app/body/view-organization-details/edit-dp/edit-dp.component.ts, src/app/body/view-organization-details/view-organization-details.component.html, src/app/body/view-organization-details/view-organization-details.component.ts, src/app/header/notification-center/notification-center.component.ts, src/app/services/auth/auth.service.ts, src/app/services/start/start-service.service.ts
Signed-off-by: Abhishek Mishra [am1426620@gmail.com](mailto:am1426620@gmail.com)
to improve functionalities in My organization page
fixed the edit org logo functionality, and added firebase indexing for techtag, also removed unnecessary console logs.
also fixed start service errors
- [] low
try the my organization page in dark mode and also try to upload a logo and check in firestore
=> fix(MyOrganization & social): fixed the edit logo in MyOrg and added indexing in techtag

functions/model/performanceChart/lib.js
Now able to use the custom filter for team performance chart more efficiently.
Changes performance chart component.
1.Open Emulator
2.create mulitple sprints  more than 5.
3. use the custom filter  in team performance chart .
4. sprint data will be represented graphically.
=> Fix(performanceChart):Fixed the Scheduler algorithm to keep the previous sprints data.

src/app/body/task-details/add-watchers/add-watchers.component.css
Adjusted the dropdown menu in big and small screen devices (Responsive).
Made changes in add-watchers.component.css file.
Visit task details page, go to add watchers popup, open the dropdown, and also check for responsiveness.
=> Fix/watcher list UI

src/app/body/board/performance-column-chart/select-dropdown/select-dropdown.component.css, src/app/body/board/performance-column-chart/select-dropdown/select-dropdown.component.html, src/app/body/profile/profile.component.ts, src/app/body/profile/skills/skills.component.html
Improve UI of filter of performance chart and skill card fix
Go to board page and check filter dropdown
Go to board page and check filter dropdown
=> UI of performance chart and skill card Done

functions/model/mailer/templates/addEducation.html, functions/model/mailer/templates/addExperience.html, functions/model/mailer/templates/addProjectProfile.html, functions/model/mailer/templates/comment.html, functions/model/mailer/templates/createTask.html, functions/model/mailer/templates/deleteTask.html, functions/model/mailer/templates/demoRequest.html, functions/model/mailer/templates/editProfile.html, functions/model/mailer/templates/editTask.html, functions/model/mailer/templates/logTask.html, functions/model/mailer/templates/updateEducation.html, functions/model/mailer/templates/updateExperience.html, functions/model/mailer/templates/updatePic.html, functions/model/mailer/templates/updateProject.html, functions/model/mailer/templates/updateSkill.html, functions/model/mailer/templates/verificationMail.html, functions/model/mailer/templates/watcher.html
Fixed and improved mail template UI.
Changes in html file of mail templates.
1.Open pulled code 
2. Go to mailer folder
3. use preview to see the html template.
=> Fixed the UI of mail templates

functions/model/mailer/templates/addEducation.html, functions/model/mailer/templates/addExperience.html, functions/model/mailer/templates/addProjectProfile.html, functions/model/mailer/templates/comment.html, functions/model/mailer/templates/createTask.html, functions/model/mailer/templates/deleteTask.html, functions/model/mailer/templates/demoRequest.html, functions/model/mailer/templates/editProfile.html, functions/model/mailer/templates/editTask.html, functions/model/mailer/templates/logTask.html, functions/model/mailer/templates/updateEducation.html, functions/model/mailer/templates/updateExperience.html, functions/model/mailer/templates/updatePic.html, functions/model/mailer/templates/updateProject.html, functions/model/mailer/templates/updateSkill.html, functions/model/mailer/templates/verificationMail.html, functions/model/mailer/templates/watcher.html
Fix and improved emails UI.
Changes in mailer folder.
1.Open Pulled Code.
2.Open mailer Folder
3.Click on preview on html templates.
4.Check the templates.
=> Fix(mailer):fixed mails UI.

src/app/body/schedule-meet/schedule-meet.component.html
Popup of schedule meet fixed
Changed the rows accordingly
Open the schedule meet popup from navbar
=> Schedule Meet popup

src/app/body/team-details/team-details.component.css, src/app/body/team-details/team-details.component.html, src/app/body/team-details/team-details.component.ts
changed the select labels  UI
made changes in team details component
ng serve -o
=> fix(labelsUI)

createRazorpayCred.js
Mechanism to change the razorpay production keys from test keys on deployment
created createRazorpayCred.js
node createRazorpayCred.js
=> feat(razorpay):mechanism to change razorpay keys

src/app/app.module.ts, src/app/body/curren-plan/curren-plan.component.ts, src/app/body/standard-subscription/standard-subscription.component.ts
fixed the release bugs
made changes in app module.ts
In Internal Release 7.2
=> fixed the release bugs

functions/model/application/paymentKeys.js
lint issues
payment.js
In Internal Release 7.2
=> lint issues

src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.css, src/app/body/create-new-team/create-new-team.component.ts, src/app/body/milestone-details/add-task/add-task.component.css, src/app/body/milestone-details/add-task/add-task.component.html, src/app/body/task-details/task-details.component.css, src/app/body/task-details/task-details.component.html
Fixed the remaining scroll bar UI issues.
Made changes in HTML and CSS files.
Open Task Details, Tech Tag, Add Task of Milestone Details pages and check the scroll bar UI.
=> Fix/other scroll bar UI

functions/model/application/paymentKeys.js, src/app/body/github-link/github-link.component.css, src/app/body/github-link/github-link.component.html, src/app/body/github-link/github-link.component.ts, src/app/services/http/http-service.service.ts
Now we can integrate even private repos from organization page
added methods for private and all repo links in httpsService
ng serve -o
=> feat(privateRepoIntegration): private and all repo integration

src/app/body/task-details/task-details.component.ts
Fixed reload issue in task-details comments.
Changes in task-details component.
2.comment on any task from my-dashboard.
3.comment will be added without reload.
=> Fix(task-details):Fixed Comments Reload

functions/model/teams/tark/creatTeamIdCheck.js, functions/model/teams/tark/createTeamNameCheck.js, functions/model/teams/teams.js, src/app/body/create-new-team/create-new-team.component.html, src/app/body/create-new-team/create-new-team.component.ts
Validate the team name and team id are unique if it is not unique then show a message to have a unique team id and name
Created new 2 API for check unique team id and name
click on create new team and enter team Name and team id
=> Create new team - validation

functions/model/teams/lib.js, functions/model/teams/tark/getAllLabels.js, functions/model/teams/tark/getAllTeamData.js, functions/model/teams/teams.js, src/app/Interface/TeamInterface.ts, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts, src/app/services/start/start-service.service.ts, src/app/services/subscription/subscription.service.ts, src/app/services/team/team-service.service.spec.ts, src/app/services/team/team-service.service.ts
Improved the Mechanism for Fetching Team Data and Label Data
Fixed Github icon in Task details page.
Improved the Mechanism for Fetching Team Data and Label Data and made it usable for all the components instead of making repeated calls for each change in team.
Fixed the github icon to only appear when the repository is linked to a particular team
Check for the Data in the testService.
=> Improved Team Data and Labels fetching mechanism

functions/model/tasks/tark/logwork.js, functions/model/teams/tark/createDefaultLabels.js, src/app/body/board/board.component.ts, src/app/body/board/sprint-burndown-chart/sprint-burndown-chart.component.ts, src/app/body/common-tools/suggestion-bucket/suggestion-bucket.component.html, src/app/body/create-new-sprint/create-new-sprint.component.html, src/app/body/create-new-sprint/create-new-sprint.component.ts, src/app/body/milestone-details/edit-milestone/edit-milestone.component.html, src/app/body/milestone-details/edit-milestone/edit-milestone.component.ts, src/app/body/milestone-details/milestone-details.component.ts, src/app/body/milestone/add-milestone/add-milestone.component.html, src/app/body/milestone/add-milestone/add-milestone.component.ts, src/app/body/profile/edit-education/edit-education.component.html, src/app/body/profile/edit-projects/edit-projects.component.html, src/app/body/profile/edit-workexperience/edit-workexperience.component.html, src/app/body/schedule-meet/schedule-meet.component.html, src/app/body/schedule-meet/schedule-meet.component.ts, src/app/body/team-details/team-details.component.ts, src/app/services/team/team-service.service.ts, src/app/services/tool/tools.service.ts
- Fixed Date format all over the application.
- Fixed Create Default Label bug.
- Fixed Date format all over the application from dd/mm/yyyy to dd-mm-yyyy.
- Fixed Create Default label bug.
Check all the functions related to dates and labels are working properly.
=> fix(improvement): fixed Dates and Labels

src/app/body/milestone/milestone.component.html
Improved milestones UI.
Changes in milestone's component
1. Open emulator.
2. Go to milestones.
3. create milestones with different status.
4. You can see the completed Milestones in different section.
=> fix(milestone):Improved milestone's UI

functions/model/teams/tark/removeMember.js
When a member is removed from a team check if the member is in any other teams if the member is not in any of the teams then remove the member and decrement the member counter
changes done in removeMember.js file
go to Teams Details page and remove member from team
=> Decrement Member counter on Member remove

src/app/body/create-new-team/create-new-team.component.html, src/app/body/create-new-team/create-new-team.component.ts
Fix Create new team UI 
changes done in create-new-team component
click on create new team
=> Fix Create new team UI 

src/app/body/team-details/team-details.component.css, src/app/body/team-details/team-details.component.html, src/app/body/update-team/update-team.component.css, src/app/body/update-team/update-team.component.html, src/app/body/view-organization-details/teams-card/teams-card.component.css, src/app/body/view-organization-details/teams-card/teams-card.component.html
On clicking edit team in teams page, its leading back to organization page and not editing the team.
Changes done in team-details-component
go to Team Details page and click on edit team
=> Fix Edit Team

functions/model/mailer/tark/generateTemplate.js, functions/model/mailer/templates/addEducation.html, functions/model/mailer/templates/addExperience.html, functions/model/mailer/templates/addProjectProfile.html, functions/model/mailer/templates/comment.html, functions/model/mailer/templates/createTask.html, functions/model/mailer/templates/deleteTask.html, functions/model/mailer/templates/demoRequest.html, functions/model/mailer/templates/editProfile.html, functions/model/mailer/templates/editTask.html, functions/model/mailer/templates/logTask.html, functions/model/mailer/templates/updateEducation.html, functions/model/mailer/templates/updateExperience.html, functions/model/mailer/templates/updatePic.html, functions/model/mailer/templates/updateProject.html, functions/model/mailer/templates/updateSkill.html, functions/model/mailer/templates/verificationMail.html, functions/model/mailer/templates/watcher.html
Fixed mails UI.
Changes in mailer component.
1.Open mailer folder in codebase.
2.Use preview extension to see the preview of mail templates .
=> Fix(mail-templates):Fixed mails UI

functions/model/performanceChart/tark/updatePerformanceChartData.js, functions/model/performanceChart/tark/updatedUserPerformanceChartData.js
Fixed team performance chart filter
Changes in tark folder of performanceChart.
2.Open my dashboard component .
3.Use schedule button which is commented.
4 generate sprints to check the filter .
=> fix(performanceChart):fixed team performance chart filter

src/app/body/create-new-task/create-new-task.component.css, src/app/body/profile/edit-profile-pic/edit-profile-pic.component.css, src/app/body/profile/edit-profile-pic/edit-profile-pic.component.html, src/app/body/profile/eductions/eductions.component.css, src/app/body/profile/eductions/eductions.component.html, src/app/body/profile/profile.component.css, src/app/body/profile/projects/projects.component.css, src/app/body/profile/projects/projects.component.html, src/app/body/profile/skills/skills.component.css, src/app/body/profile/work-exp/work-exp.component.css, src/app/body/profile/work-exp/work-exp.component.html
Fix profile-pic popup, remove border from card, fix dates
remove border and make dates in one line
by entering details in profile
=> Fix profile ui and Dates

src/app/body/create-new-task/create-new-task.component.css
fix create new task popup
remove green button from close button
by creating a new task
=> fix create new task popup

src/app/body/view-organization-details/teams-card/teams-card.component.css
fixed merge conflcts
fixed merge conflcts
ng serve -o
=> Fix/release bugs7.3.4

src/app/body/milestone-details/edit-milestone/edit-milestone.component.html, src/app/body/milestone-details/milestone-details.component.html, src/app/body/milestone-details/milestone-details.component.ts, src/app/body/milestone/add-milestone/add-milestone.component.css, src/app/body/milestone/add-milestone/add-milestone.component.html
Fix milestone graph algorithm
Changes done in milestone-details-component
go to milestone page and add new task or mark it completed
=> Fix milestone graph algorithm

src/app/body/view-organization-details/teams-card/teams-card.component.css, src/app/body/view-organization-details/teams-card/teams-card.component.html
fix delete team popup ui
make similar to other popups
by going organization page and delete team
=> Delete team popup ui

src/app/body/milestone/milestone.component.css, src/app/body/milestone/milestone.component.html, src/app/body/milestone/milestone.component.ts, src/app/body/schedule-meet/schedule-meet.component.css
fix ui of calender icon of schedule meet and "completed" heading of milestone in dark mode
make visible to calender icon and completed show in dark mode when milstone is completed
by scheduling meet and by creating a completed milestone
=> Fixes UI in popups

.github/pull_request_template.md, src/app/Interface/githubOrgData.ts, src/app/body/task-details/git/git.component.css, src/app/body/task-details/git/git.component.html, src/app/body/task-details/git/git.component.ts, src/app/body/task-details/task-details.component.css, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts
Get pr found using WtId.
Changes in git & task-details component and also the pr template in github
1.Create a pull request in github with your Worktez Id.
2.Go to worktez.com 
3. Open task details of task mentioned with Worktez Id.
4. Click on pull request icon
5. You can see your pr found in the list.
=> Feat(git):Get pr found using WtId

src/app/body/team-details/label-card/label-card.component.css, src/app/body/team-details/label-card/label-card.component.html
Delete Popup Label Fixed
Fixed Modal of Delete Popup
Go to my organisation and check
=> fixed(Label/Popup)

functions/model/meet/lib.js, src/app/header/show-meet-details/show-meet-details.component.css, src/app/header/show-meet-details/show-meet-details.component.html, src/app/header/show-meet-details/show-meet-details.component.ts
Schedule Meeting Fixed with delete functionality
Create a Meet and check
Create meet and check the functionality
=> ScheduleMeet(fixed)

firestore.indexes.json
fix Internal release bugs
Fixed Indexing
In Internal Release 7.5
=> fix(Index): FIxed indexing

functions/model/teams/tark/updateTeam.js, src/app/body/team-details/team-details.component.ts, src/app/body/update-team/update-team.component.html, src/app/body/update-team/update-team.component.ts
Add Team Manager field in update team popup
Required changes done
Dev588
go to Team-Details Page and click on edit icon
=> Add Team Manager field in update team popup

functions/model/teams/lib.js, functions/model/teams/tark/addGitToken.js, functions/model/teams/teams.js, src/app/Interface/TeamInterface.ts, src/app/app.module.ts, src/app/body/github-link/github-link.component.html, src/app/body/github-link/github-link.component.ts, src/app/body/task-details/create-git-issue/create-git-issue.component.css, src/app/body/task-details/create-git-issue/create-git-issue.component.html, src/app/body/task-details/create-git-issue/create-git-issue.component.spec.ts, src/app/body/task-details/create-git-issue/create-git-issue.component.ts, src/app/body/task-details/git/git.component.css, src/app/body/task-details/git/git.component.html, src/app/body/task-details/git/git.component.spec.ts, src/app/body/task-details/git/git.component.ts, src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts, src/app/body/team-details/team-details.component.css, src/app/body/team-details/team-details.component.html, src/app/body/team-details/team-details.component.ts, src/app/services/http/http-service.service.ts
Allow the user  to create an issue from the task into GitHub.
Dev555
go to Team-Details page and add git token and go to task-Detail page and click on three dot and click on report to git option
=> Integration of GitHub issues

functions/model/meet/lib.js, src/app/body/schedule-meet/schedule-meet.component.css, src/app/header/header.component.css, src/app/header/header.component.html, src/app/header/header.component.ts, src/app/header/show-meet-details/show-meet-details.component.css, src/app/header/show-meet-details/show-meet-details.component.html, src/app/header/show-meet-details/show-meet-details.component.ts
to fix the UI and delete functionality of schedule meeting
fixed the UI and fetching of schedule meetings from database, delete functionality was there already
Dev587
in the header click on scheduled meetings and try to delete a scheduled meeting
=> fix(schedule-meeting):fixed the UI and delete functionality

functions/model/organization/lib.js, functions/model/organization/organization.js, functions/model/organization/tark/removeOrgMember.js, src/app/Interface/UserInterface.ts, src/app/body/view-organization-details/members-access/members-access.component.css, src/app/body/view-organization-details/members-access/members-access.component.html, src/app/body/view-organization-details/members-access/members-access.component.ts, src/app/body/view-organization-details/teams-card/teams-card.component.html
Added feature to delete user from organisation and teams.
Changes in members-access component an implementation of method in tark of organization.
2.Go to member access in my organization
3.you can see the delete button only when the the role is set as admin.
4.the delete button will delete the user from the organisation as well as from teams.
=> feat(removeOrgMember):Added feature to delete user from organisation and teams

src/app/body/social-page/create-post/create-post.component.css, src/app/body/social-page/create-post/create-post.component.html, src/app/body/social-page/create-post/create-post.component.ts, src/app/body/social-page/social-page.component.css, src/app/body/social-page/social-page.component.html, src/app/body/social-page/social-page.component.ts
Improved UI of create-post
changes in social-page and create-post component.
2. go to techtag
3. you can see the updated UI of create-post.
=> fix(create-post):improved UI of create-post

src/app/body/social-page/posts/posts.component.html
Signed-off-by: RaunakSharma002 <raunaksharma22345@gmail.com>
adding loader for comment
enable loader for comment
Dev599
going into tec tag and comment into post
=> add loader for comment section

functions/model/organization/tark/removeOrgMember.js, functions/model/users/lib.js, src/app/body/view-organization-details/members-access/members-access.component.css, src/app/body/view-organization-details/members-access/members-access.component.html, src/app/body/view-organization-details/members-access/members-access.component.ts
Deletes the user from organisations as well as teams.
changes in member-access component and removeOrgMember.js
1. Open emulator and create multiple users
2. Go to member-access in My organisation
3. delete a user and check the firestore in firebase emulators
=> fix(member-access):fixed delete button in member-access

src/app/body/github-link/github-link.component.css, src/app/body/github-link/github-link.component.html, src/app/body/gitlab-link/gitlab-link.component.html, src/app/body/team-details/github-integration/github-integration.component.css, src/app/body/team-details/github-integration/github-integration.component.html, src/app/body/team-details/github-integration/github-integration.component.ts, src/app/body/team-details/gitlab-integration/gitlab-integration.component.css, src/app/body/team-details/gitlab-integration/gitlab-integration.component.html, src/app/body/team-details/gitlab-integration/gitlab-integration.component.ts, src/app/body/team-details/team-details.component.css
Fixed the UI issues in the Team Details and also fixed the Token issue after adding the Git Token.
Made changes in ts and html files. 
Go to the team details page and add token to see the changes.
=> Fixed UI and Git Token Issues

src/app/body/team-details/github-integration/github-integration.component.html, src/app/body/team-details/github-integration/github-integration.component.ts, src/app/body/team-details/gitlab-integration/gitlab-integration.component.html, src/app/body/team-details/gitlab-integration/gitlab-integration.component.ts
Unlinking github repository
made a remove button to perform unlinking
ng serve -o
=> feat(unlink): unlinking repository

src/app/header/notification-center/notification-card/notification-card.component.html, src/app/header/notification-center/notification-center.component.css, src/app/header/notification-center/notification-center.component.html, src/app/header/notification-center/notification-center.component.ts, src/app/services/start/start-service.service.ts
Fixed UI and loading issue of new notifications
changes in notification-center component
2.Check notifications
=> fix(notifications):Fixed loading of new notifications

src/app/body/profile/edit-profile/edit-profile.component.css, src/app/body/profile/edit-profile/edit-profile.component.html, src/app/body/profile/profile.component.html, src/app/body/profile/profile.component.ts
fix Git link in profile page 
Dev596
go to profile page and click on link github then it shows git icon and if click on unlink github it disappear that icon
=> Fix Git link in profile Page

functions/model/quickNotes/quickNotes.js, functions/model/quickNotes/tark/addNote.js, functions/model/quickNotes/tark/deleteNote.js, functions/model/quickNotes/tark/reorderQuicknotes.js, functions/model/users/lib.js, src/app/Interface/UserInterface.ts, src/app/body/quick-notes/addnew-note/addnew-note.component.ts, src/app/body/quick-notes/quick-notes.component.html, src/app/body/quick-notes/quick-notes.component.ts, src/app/services/quickNotes/quick-notes.service.ts
Signed-off-by: Abhishek Mishra [am1426620@gmail.com](mailto:am1426620@gmail.com)
to implement drag and drop feature in quicknotes
implemented the drag-drop feature using cdkDragDrop and saved the new notesOrder in database everytime it is changed
Dev594
try adding, deleting, and drag-drop the notes in quicknotes section
=> feat(drag-drop):'implemented drag and drop feature in quicknotes'

src/app/body/curren-plan/curren-plan.component.html, src/app/body/curren-plan/curren-plan.component.ts
Signed-off-by: RaunakSharma002 <raunaksharma22345@gmail.com>
show Contact Us page when click to contact button
link Request Demo page with Contact button
Dev597
go into My Organization click into Contact button in subscription page
=> Contact page for Subscription

src/app/body/create-new-team/add-member/add-member.component.css, src/app/body/create-new-team/add-member/add-member.component.html, src/app/body/create-new-team/add-member/add-member.component.ts
show message if member already added in team
show a popup if member already added
Dev611
go into My Organization and try to add member into team which is already added
=> Show member already added

angular.json, package-lock.json, package.json, src/robots.txt, src/sitemap.xml, src/test.ts, tsconfig.json
Update Angular v14 to v15
Updated packages for angular v15
application performance is enhanced
=> Update angular v14 to v15

angular.json, src/robots.txt, src/sitemap.xml
Added sitemap for improved seo
Better seo for google search
Google search console
=> Added sitemap for better seo

functions/model/teams/tark/editLabel.js, functions/model/teams/tark/getAllLabels.js, functions/model/teams/tark/reorderLabels.js, functions/model/teams/teams.js, src/app/body/team-details/edit-label-prop/edit-label-prop.component.ts, src/app/body/team-details/label-card/label-card.component.css, src/app/body/team-details/label-card/label-card.component.html, src/app/body/team-details/label-card/label-card.component.ts, src/app/body/team-details/team-details.component.html, src/app/icons/generate-icon/generate-icon.component.ts, src/app/services/team/team-service.service.ts
Signed-off-by: Abhishek Mishra [am1426620@gmail.com](mailto:am1426620@gmail.com)
to implement drag and drop feature in team labels
implemented drag and drop feature for team labels, also fixed the data fetching mechanism for team labels using team service
Dev600
go to teams page, check if labels are loaded, then try dragging and dropping them
=> feat(drag-drop): Drag drop labels

src/app/body/task-details/log-work/log-work.component.css, src/app/body/task-details/log-work/log-work.component.html
remove green border from log-work
removed border
Dev627
by logging the work in my dashboard
=> Fix log works UI

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/body/login/login.component.css, src/app/body/login/login.component.html, src/app/body/login/login.component.ts, src/app/body/reset-password/reset-password.component.css, src/app/body/reset-password/reset-password.component.html, src/app/body/reset-password/reset-password.component.spec.ts, src/app/body/reset-password/reset-password.component.ts, src/app/header/login-handler/login-handler.component.css, src/app/services/auth/auth.service.ts
Signed-off-by: Abhishek Mishra [am1426620@gmail.com](mailto:am1426620@gmail.com)
to implement password reset functionality for forgotten passwords
implemented password reset methods using firebase functions
Dev607
try changing password for a non google sign-in user.
=> feat(reset-password): "Implemented reset password functionality"

src/app/body/view-organization-details/teams-card/teams-card.component.html, src/app/body/view-organization-details/teams-card/teams-card.component.ts
fix delete team: only first team was deleted when deleted any team
give the proper instruction to delete function which team has to be deleted
Dev633
by deleting any team
=> Fix delete team

functions/model/application/lib.js, functions/model/organization/organization.js, functions/model/organization/tark/createOrg.js, functions/model/organization/tark/orgDomainCheck.js, src/app/body/create-new-organization/create-new-organization.component.css, src/app/body/create-new-organization/create-new-organization.component.html, src/app/body/create-new-organization/create-new-organization.component.ts, src/app/services/auth/auth.service.ts, src/app/services/start/start-service.service.ts
Org Domain Validation
Dev632
go to CreateNewOrganization page and create new Organization
=> Org Domain Validation

src/app/body/features-page/boards-feature/boards-feature.component.html, src/app/body/features-page/boards-feature/boards-feature.component.ts, src/app/body/features-page/charts-feature/charts-feature.component.html, src/app/body/features-page/charts-feature/charts-feature.component.ts, src/app/body/features-page/devops-feature/devops-feature.component.ts, src/app/body/features-page/features-page.component.css, src/app/body/features-page/features-page.component.html, src/app/body/features-page/meetings-feature/meetings-feature.component.html, src/app/body/features-page/meetings-feature/meetings-feature.component.ts, src/app/body/features-page/milestones-feature/milestones-feature.component.ts, src/app/body/features-page/organisations-feature/organisations-feature.component.html, src/app/body/features-page/organisations-feature/organisations-feature.component.ts, src/app/body/features-page/profile-feature/profile-feature.component.html, src/app/body/features-page/profile-feature/profile-feature.component.ts, src/app/body/features-page/quicknotes-feature/quicknotes-feature.component.html, src/app/body/features-page/quicknotes-feature/quicknotes-feature.component.ts, src/app/body/features-page/tasks-feature/tasks-feature.component.html, src/app/body/features-page/tasks-feature/tasks-feature.component.ts, src/app/body/features-page/techtag-feature/techtag-feature.component.ts, src/app/body/get-started/get-started.component.css, src/app/body/get-started/get-started.component.html, src/app/body/get-started/get-started.component.ts
to fix the errors in content of getting started and docs page
fixed the grammatical errors with the help of proofread document provided
read the contents of docs page for any grammatical errors
=> fix(docs): 'content modifications in getting started and features page'

src/app/body/board/board.component.html, src/app/body/board/board.component.ts
Fixed UI for sprint if it  doesn't exist.
Changes in board component.
1.open emulator
2.Go to board from Boards Dropdown
3.use sprint filter to redirect to sprint which does not exist.
=> fix(board):fixed UI for sprint if it  doesn't exist

src/app/body/task-details/git/git.component.ts
fixed rendering of found Pr referring WtId.
Changes in Git Component.
1.Open emulator.
2.Setup Github repo from my oeganization.
3.Raise a dummy pr in worktez with WtId.
4.Check in the Task Details with TaskId similar to WtId.
=> fix(git)fixed rendering of found Pr referring WtId

src/app/body/login/login.component.html, src/app/body/quick-notes/quick-notes.component.css, src/app/body/quick-notes/quick-notes.component.html, src/app/body/release-details/release-details.component.html, src/app/body/release-details/release-details.component.ts
ui fixes as discussed in innovation meeting
made quicknotes scrollable, show password checkbox for login, and release credits in seperate lines
try adding multiple notes in quicknotes,
try login with password,
go to release page and check release credits.
=> fix(ui): 'UI fixes in quicknotes, login, releases'

src/app/body/task-details/task-details.component.html, src/app/body/task-details/task-details.component.ts
Fixed git icons rendering
Changes in task-details component
1.open emulator
2.create team in my organisation
3.integrate github or gitlab in teams
4.go to my dashboards from boards
5. check task from task details from the respective team
=> fix(task-details):Fixed git icons rendering

src/app/app.module.ts, src/app/body/error-modal/error-modal.component.css, src/app/body/error-modal/error-modal.component.html, src/app/body/error-modal/error-modal.component.spec.ts, src/app/body/error-modal/error-modal.component.ts, src/app/body/login/login.component.html, src/app/body/login/login.component.ts, src/app/header/login-handler/login-handler.component.html, src/app/services/auth/auth.service.ts
Fixed UI of Authentication Errors.
Changes in Login component and auth.service.ts file.
1.Open Emulator
2.Click on login
3.Signup with your credentials and logout.
4.Check error modal entering wrong credentials to login again.
=> fix(login):fixed UI of Authentication Errors

functions/model/meet/tark/scheduleMeet.js
Fixed the Schedule meet functionality
Added Meeting data to meeting participants
DEV645
- Schedule a meet
- Check whether the participants are able to view the meet details in nav bar
=> Fix(Meets):Fixed Schedule Meet

src/app/body/team-details/add-label/add-label.component.css, src/app/body/team-details/edit-label-prop/edit-label-prop.component.css, src/app/body/team-details/edit-label-prop/edit-label-prop.component.html, src/app/body/team-details/label-card/label-card.component.html, src/app/body/team-details/label-card/label-card.component.ts
Edit label should have a pre info and remove green color from close button
There was a mistake in code which has been corrected
Dev648
Go into my Organization and try to edit label
=> Edit Label functionality and improve button ui

src/app/body/release-details/edit-release/edit-release.component.html, src/app/body/release-details/edit-release/edit-release.component.ts, src/app/body/release-details/release-details.component.html, src/app/body/release-details/release-details.component.ts, src/app/body/release/add-release/add-release.component.ts, src/app/body/release/release-card/release-card.component.html, src/app/body/release/release-card/release-card.component.ts, src/app/body/release/release.component.ts, src/app/services/gitlab-service/gitlab-service.service.ts, src/app/services/start/start-service.service.ts, src/app/services/team/team-service.service.ts
Gitlab release integration
Made changes in the release component based on the provider
Go to pipelines section and check
=> feat(gitlabReleaseIntegration): gitlab release integration

src/app/body/github-link/github-link.component.ts, src/app/body/gitlab-link/gitlab-link.component.ts, src/app/body/task-details/gitlab/gitlab.component.html, src/app/body/task-details/gitlab/gitlab.component.ts, src/app/body/task-details/task-details.component.ts, src/app/services/gitlab-service/gitlab-service.service.ts
Gitlab PR linking in task details page
Made changes gitlab component
ng serve -o
=> feat(GitlabprLinking): link gitlab merge requests

src/app/body/home/home.component.css, src/app/body/team-details/label-card/label-card.component.css
Small UI Fixes
on home page card arrow fix and TeamDetails  page  Labels icon fix
=> Small UI Fixes

src/app/body/task-details/gitlab/gitlab.component.ts
Fixed gitlabs remove link issue
Changes in gitlab component
1. Open Emulator
2. go to my Organization.
3. Integrate gitlabs in the teams.
4. add merge request from the task details
=> Fix(gitlabs):Fixed gitlabs remove link issue

src/app/body/pipeline/pipeline.component.css, src/app/body/pipeline/pipeline.component.html, src/app/body/pipeline/pipeline.component.ts, src/app/header/header.component.html
Fixed the deploy icon, dark mode and nav bar
made changes in the pipeline component
ng serve -o
=> fix(pipeline): pipeline UI fixes

src/app/body/pipeline/pipeline.component.css, src/app/body/pipeline/pipeline.component.html, src/app/header/header.component.html
pipeline ui fixes
made changes in pipeline component
=> pipeline ui fixes

functions/index.js, functions/model/application/lib.js, functions/model/rewards/lib.js, functions/model/rewards/rewards.js, functions/model/rewards/tark/addDigitalAssets.js, functions/model/users/lib.js, functions/model/users/tark/addUserRewards.js, functions/model/users/users.js
creation of digital assets and assigning rewards to users
Changes in model file.
1. create callable's in setup.component.ts
2. Open emulator
3. Click on Autosetup
4. check firesstore collection from firebase emulator .
=> feat(Digital-Assets):api to create Digital asset

src/app/body/common-tools/icons-base/icons-base.component.css, src/app/body/pipeline/pipeline.component.html, src/app/body/pipeline/pipeline.component.ts, src/app/body/task-details/task-details.component.ts, src/app/services/gitlab-service/gitlab-service.service.ts
Pipeline integration for GitLab
Dev650
link Gitlab project and go to pipeline page
=> Feat(gitlab-pipeline): Integrating GitLab Pipeline for Streamlined Project Development

src/app/body/pipeline/pipeline.component.html, src/app/body/pipeline/pipeline.component.ts
Fix the bug of Piplines
TeamId was undefined reload, fix the teamName
Dev668
By going into pipelines and reload page
=> Pipeline has no data upon reload

firestore.indexes.json
Fixed milestone's rendering issue
Added firebase indexes in firestore.indexes.json
1.Open Emulator
2.Create Milestone
3.Check the milestone list.
=> fix(milestone):fixed milestone's rendering issue
